testssl.sh

Idea is to bail out per default (with WARNINGS=off) this makes batch processing possible
as often testssl.sh hangs for minutes or endless on non-SSL ports.

Change question logic on non-SSL port

---

testssl.sh

In LibreSSL, GOST support is in built-in engine.

Fix GOST handling in LibreSSL

---

testssl.sh

I'm starting to push testssl.sh through shellcheck.sh's static analysis. The 2>&1 commit was actually wrong -- I had forgotten about the order issue.
The backticks to $(..) is really a style/modernization nitpick, but there are some other things that will be coming such as unquoted variables, misuse of variables in printf, etc. Ideally we'll have testssl.sh throwing no warnings when run through shellcheck and there will fewer issues to troubleshoot in the future. :-)

Shellcheck static analysis

---

testssl.sh

(new pull request, based on correct upstream/master branch)
Note that due to the refactoring of some status messages, the output will be slightly different (more verbose) than previous versions
Moved specific status messages to http_header()
Moved specific status messages to breach()
Moved specific status messages to ccs_injection()
Moved specific status messages to heartbleed()
Moved specific status messages to renego()
Moved specific status messages to crime()
Moved specific status messages to tls_poodle()
Moved specific status messages to freak()
Moved specific status messages to beast()
Added some more documentation for functions
Fixed typos in help
Created new function main:
This is the main function of testssl.sh
Refactored major part of the original main function
Created new …

Refactored major parts of code

---

Readme.md

To effectively analyze the LOGJAM risks, and to display the bitstrength on the DH/ECDH negotiated ciphers, OpenSSL 1.0.2+ is needed.  With anything under 1.0.2 (and greater than 1.0.0), the bitstrengths are not displayed as OpenSSL is 'too old' (as referred to in the script itself when 1.0.2 is newer than what's available).
I suggest that we keep a note that >= 1.0.2 is needed for LOGJAM checks to be truly effective (and to display bitstrengths)

Update OpenSSL reqs - LOGJAM checks need 1.0.2+

---

testssl.sh

Suppress awk warnings
Don't try to retrieve header information from openssl stderr output

Another fix for #140

---

testssl.sh

Fix for #166
On OSX the following line doesn't seem to work (i.e. the input is good the output is empty), however [others have it working on OSX with separated -e args like you've got](http://stackoverflow.com/questions/1251999/how-can-i-replace-a-newline-n-using-sed). I went to change it from sed to tr, however realised we didn't need the new line at all.
```
L1794: sans=$(echo "$sans" | sed -e ':a' -e 'N' -e '$!ba' -e 's/\n/ /g') # replace line feed by " "
```

Fix subject alternative name on darwin

---

testssl.sh

Trivial typo. All other CVE outputs are in the form CVE-XXXX-YYYY

Typo. Inconsistent CVE string format

---

testssl.sh

The sentence did not read correctly with the number of available ciphers where it was, so I moved it to where I feel it should be.

Changed wording for easier readability.

---

testssl.sh

Avoid "tput: No value for $TERM and no -T specified" when running from CGI or similar by checking for interactive shell

Fix: tput: No value for $TERM and no -T specified

---

CREDITS.md
testssl.sh

@drwetter you can add this one first if you do'nt want to go through #242 first. but #259 adds support for JSON/CSV as well.
And... No backticks in this one ;)

Redirect test that doesn't depend om JSON/CSV output

---

testssl.sh

OpenSSL doesn't show the ALPN advertised protocols, so I try to test the common ones (HTTP/2, recent HTTP/2 drafts, SPDY/3.1, and HTTP/1.1). I also changed some of the SPDY code because connecting to `$NODE` will cause `gethostbyname` errors with the static binaries, and the extra line that `run_spdy` prints seems redundant.

Add HTTP2/ALPN support

---

testssl.sh

Hi Dirk,
this PR add a colorblind option (--colorblind) to swap green and blue in the output (just in the ANSI part). This close #236.

added colorblind option

---

testssl.sh

This should fix issue #278. I'm not sure whether openssl verify will ever print out more than one error, so to be safe, I wrote the code to handle the possibility that it might; if there is more than one error, it just takes the first and ignores the rest.

Fix chain of trust problem

---

testssl.sh

I think this is a typo.
Saw an error when I tried a test using the latest from `master` so I skimmed the source code and assumed the `debug` should've been `debugme` - changing it removed the warning.

fix typo in b93fc824

---

testssl.sh

This corrects the indentation within determine_trust() when there are multiple certificates and the output for "Chain of trust (experim.)" takes up more than one lines.
In addition, it fixes the ID field of the JSON output for entries related to the certificate. At the moment, each ID string begins with a blank space. This changes it to remove the space if there is one certificate and to add "Server Certificate #X" at the beginning of each ID if there is more than one certificate.
Perhaps there's a better way than just using, for example, "Server Certificate #1 key_size" as a way to distinguish multiple "key_size" entries in the JSON file. This is just one idea, and it can certainly be changed if those who intend to use the JSON output prefer something else.

Detect multiple certificates cleanup

---

testssl.sh

In using scripts with testssl.sh, I found that the case of severity codes was not always consistent, e.g. 'info' vs 'INFO'.  I tried to find all inconsistent use of case in the severity codes and informative comments.

Consistent case severity codes

---

Readme.md

Hi,
just noticed that the formatting of the readme is not really nice to read in terminal.
I did a quick reformat to make headlines valid (with a space) and rearranged textblocks to 
match 80 chars per line limit.

Format readme for better readability

---

testssl.sh

The run_allciphers() function currently works by calling "$OPENSSL s_client" once for each cipher suite supported by $OPENSSL. In the case of "OpenSSL 1.0.2-chacha (1.0.2e-dev)" that means 195 calls to "$OPENSSL s_client" even though servers tend to only support a small fraction of these cipher suites.
This PR produces the same output as the current run_allciphers() with fewer calls to "$OPENSSL s_client", which results in the function running faster (usually much faster). The basic idea behind the revised function is to test cipher suites in blocks. If $OPENSSL supports 195 cipher suites, then it groups these cipher suites into 4 blocks of 64 (with the final block being smaller). It makes one call to "$OPENSSL s_client" with cipher suites 1-64, and if it fails, then it knows that none of …

run_allciphers() speedup

---

testssl.sh

The last line of neat_list currently uses $HEXC as the parameter to show_rfc_style(), but it should use $hexcode. At the moment using $HEXC instead of $hexcode makes no difference, since hexcode="$1" and in all calls to neat_list() the first parameter is $HEXC. However, this bug could create problems in the future since neat_list() will misbehave if the value of the first parameter (hexcode) isn't the same as $HEXC.

Fix typo in neat_list()

---

testssl.sh

*** Updated to align with yesterday's changes to run_allciphers() ***
This PR makes basically the same changes to run_cipher_per_proto() as I previously made to run_allciphers(). The main difference is that in this function, round 0 consists of a single call to "$OPENSSL s_client" with "-cipher" including all of the locally supported ciphers. The reason for the difference is that in run_allciphers() its saves time to assume the server supports at least one cipher suite. In the case of run_cipher_per_proto(), however, it is likely that the server will not support some protocols at all, so its usually faster to start with a single call to "$OPENSSL s_client" that tests whether the server supports the protocol at all.

run_cipher_per_proto speedup

---

testssl.sh

logfile, jsonfile and csvfile parameters work without =

---

testssl.sh

This PR provides a revised version of parse_tls_serverhello() that should be more robust in terms in variations in the response provided by the server and that includes several checks to verify that the response is valid. This should address issues #348 and #340.
I tested this code against quite a few servers (more than 50) and verified that the results are the same as with the current code.
This version of parse_tls_serverhello() is a simplified version of the one that I am working on at https://github.com/dcooper16/testssl.sh/blob/extended_tls_sockets/testssl.sh, which parses a lot more of the server's response, and so also includes many more validity checks.

parse_tls_serverhello() with added checks

---

testssl.sh

When certificate_info() is trying to determine what type of public key the server has so that it can determine whether the key size is acceptable, it sometimes looks at $cert_sig_algo rather than $cert_key_algo. This PR fixes that and also adds support for DSA public keys.

Fix typo in Server key size check

---

testssl.sh

When run_rc4() is run with the "--show-each" option, but without the "--wide" option, a list of all RC4 ciphers is printed, without any distinction between those that are supported by the server and those that are not. This is the same issue I noted in #332 for run_pfs().
In run_pfs(), the displayed output was corrected, but all ciphers were still being added to $pfs_ciphers, so the list of supported PFS ciphers sent to fileout() was incorrect.
This PR fixes both issues.

run_pfs() and run_rc4() show each fixes

---

testssl.sh

This patch should fix https://github.com/drwetter/testssl.sh/issues/365, the IPv6 lookup problem. 
Without this patch, PTR records cannot be found for IPv6 addresses due to superfluous brackets around the address. Furthermore, the patch supports freaky OpenSSL builds, like Gentoo’s, where the binary doesn’t support the bracketed IPv6 address as part of the -connect parameter and requires the unbracketed address instead.
Dirk, if you don’t like https://github.com/drwetter/testssl.sh/commit/2c69e83f5b98974ffe87422fa45a30d4824ed4a9, please at least merge https://github.com/drwetter/testssl.sh/commit/cf62353fc6d55322b927baad8467f67521a7b497 because that will be required by anybody who wants to see rDNS for his IPv6 test runs.

drwetter#365 fix ipv6 handling

---

testssl.sh

This PR adds the signature algorithms, heartbeat, session ticket, and next protocol extensions to the client hello message created by socksend_tls_clienthello() for TLS 1.0 and above. It also adds the supported elliptic curves and ec points format extensions if the client hello message includes any ECC cipher suites.
I tested this version against several servers with $EXPERIMENTAL set to true and get the same results as with the current code with $EXPERIMENTAL set to false.

More extensions in socksend_tls_clienthello()

---

testssl.sh

Hi @drwetter,
This PR adds curves x25519 and x448 to the ClientHello created by socksend_tls_clienthello(), as you requested in #342.
I added both EC 1d and EC 1e since both are listed in the IANA registry: http://www.iana.org/assignments/tls-parameters/tls-parameters.xhtml#tls-parameters-8.

Adding x25519 and x448 to ClientHello

---

testssl.sh

Here is the PR to address #378.
I went ahead and added in a call to `has_server_protocol()`, and I fixed a couple of minor bugs related to that function:
- the `grep` in `has_server_protocol()` was missing the `-q` option.
- run_protocols() was adding tls1 to $PROTOS_OFFERED if the server downgraded to SSLv3.

run_cipher_per_proto() 128-cipher limit

---

testssl.sh

The current code in certificate_info() for extracting the subjectAltName extension from a certificate is:
```
sans=$($OPENSSL x509 -in $HOSTCERT -noout -text 2>>$ERRFILE | grep -A3 "Subject Alternative Name" | grep "DNS:" | \
sed -e 's/DNS://g' -e 's/ //g' -e 's/,/ /g' -e 's/othername:<unsupported>//g')
```
with this code, the contents of the subjectAltName extension are not printed unless the extension contains a DNS name. If a DNS name is present, then the string "DNS:" is removed from any DNS names and any instance of "othername:<unsupported>" is not displayed, but all other names in the subjectAltName extension are displayed as they are output by OpenSSL (with the exception of directory names, where all space characters are removed from the names). For example, if OpenSSL displays the …

Printing of subjectAltName extension

---

testssl.sh

Bash somewhat counterintuitively uses the return code 0 to mean true (no errors) and any other value (1, -1, ...) to mean false. The return values are used on lines 898/903 for HSTS and 986/991 for HPKP.

Fix HSTS/HPKP includeSubDomains and preload being broken in file output.

---

testssl.sh

Had to kill the run_mass_scan_parallell routine due to concurrency problems.

Allow the file output feature and mass_test feature to work together

---

testssl.sh

Missing a closing parentheses `)`.
------
This is a very minor issue and doesn't affect functionality.  The lack of a closing parentheses character was irking me on that one line of the help output.

Missing closing parenteses in help output for --openssl

---

testssl.sh

On FreeBSD, sed does not support "\n" in the replacement string of a substitution. The SANs are currently output all together inside a single pair of quotes and each separated with an "n" character, needless to say this is very difficult to read.
After a little digging, it seems this is a somewhat recent regression of the fix in #173. I believe `tr` would be a more cross-platform way to do this, and several sources (including the author of that PR) would seem to agree - assuming the newline is now necessary.
It doesn't appear to matter what order the newline replacement happens amongst all the other replacements, so I have placed it first simply to avoid extending any already-long lines. Please correct me if this deduction is false.

Unreadable SAN list on FreeBSD

---

testssl.sh

I noticed the NPN parts of the cipher order tests were not returning any ECDSA ciphers where I expected them to match the results of the immediately preceding TLS 1.2 test. Found it wasn't using SNI so my test server was using the default domain (snakeoil RSA certificate) instead of the tested domain (dual ECDSA/RSA certificates).
I have used other s_client calls as a template, so `-host`/`-port` are replaced with `-connect` (the only remaining use of `-host` elsewhere is commented out). `$PROXY` has also been removed from the inner 2 calls due to finding a comment asserting that proxies don't support NPN. If any of these were deliberately so, please correct me.

Server cipher order NPN tests should use SNI

---

testssl.sh

Rather than try each curve one at a time, this PR follows model in `cipher_pref_check()`.  First include all curves in ClientHello, then successively remove from the ClientHello those curves that have been offered by the server until the connection fails. This makes the number of calls to `$OPENSSL s_client` one more than the number of supported curves rather than the number of curves in NamedCurve supported by $OPENSSL.
Note, however, that OpenSSL defines MAX_CURVELIST as 28 and fails if the `-curves` option includes more than 28 curves. Since OpenSSL 1.1.0 offers 29 curves from NamedCurve, this PR breaks the list of supported curves in 2. At the cost of one additional calls to `$OPENSSL s_client` it ensures that the number of curves provides to the `-curves` option is below the limit.

Speed up finding supported curves

---

testssl.sh

`certificate_info()` currently outputs `$issuer` to the JSON file, where is should be outputting `$issuer_CN` in order for the information in the JSON file to match the information that is displayed.
This PR also fixes the problem that if an Issuer name contains a domain component attribute (DC=) then it will be mistakenly treated as a country attribute (C=).

Fix JSON output of Issuer name

---

testssl.sh

The check for whether a certificate is self-signed was using the undefined variable `$CN` rather than `$cn`.
Note: I didn't change the rest of the line, but I can't understand why `issuer_O` being `issuer=` or `issuer= ' would indicate that a certificate is self-signed certificate.
It seems that a better check would be to compare the entire issuer name to the entire subject name, since the names could be different even if they have the same `CN` attribute:
```
issuer=$($OPENSSL x509 -in "$HOSTNAME" -noout -issuer | sed '/^issuer= //')
subject=$($OPENSSL x509 -in "$HOSTNAME" -noout -subject | sed 's/^subject= //')
if [[ "$issuer" == "$subject ]]; then
else
fi
```

Fix check for self-signed certificate

---

testssl.sh

This PR changes test_just_one() to correctly handle SSLv2 ciphers.
As with PR #424, this PR addresses the problem in which servers that do not implement SSLv2, but that implement RC4-MD5, EXP-RC2-CBC-MD5, EXP-RC4-MD5, or NULL-MD5 are shown as implementing both the SSLv2 and SSLv3 versions of the ciphers, and that any SSLv2 ciphers that a server does implement are not shown as being implemented.

SSLv2 fixes for test_just_one()

---

testssl.sh

This PR changes run_rc4() to correctly handle SSLv2 ciphers.
It addresses the problem in which servers that do not implement SSLv2, but that implement SSLv3 ciphers that share an OpenSSL name with an SSLv2 cipher (RC4-MD5 and EXP-RC4-MD5), are not incorrectly shown as having implemented the SSLv2 cipher.
It also addresses the problem that if a server does implement SSLv2 with an RC4 SSLv2-cipher suite, then that cipher suite it not shown as being implemented.

SSLv2 fixes for run_rc4()

---

testssl.sh

In the check for old versions of OpenSSL, the results of the call to `ignore_no_or_lame()` are ignored, and so the program continues even if the user enters `no`.

Don't ignore response to old OpenSSL warning

---

testssl.sh

This PR makes three changes to `determine_optimal_proto()`:
* It no longer tries an empty string for `$OPTIMAL_PROTO` twice.
* It does not include `-servername` for `-ssl2` or `-ssl3`, since some versions of OpenSSL that support SSLv2 will fail if `s_client` is provided both the `-ssl2` and `-servername` options.
* It displays a warning if `$OPTIMAL_PROTO` is `-ssl2`, since some tests in testssl.sh will not work correctly for SSLv2-only servers.

 SSLv2 fixes for determine_optimal_proto()

---

testssl.sh

If the version of OpenSSL being used doesn't support `s_client -ssl3` (e.g., OpenSSL 1.1.0), `run_beast()` doesn't display a warning that testing for CBC in SSLv3 isn't locally supported.
This PR adds a "Local problem" warning if the OpenSSL being used doesn't support `s_client -ssl3`.

Warning on BEAST when no local SSLv3 support

---

testssl.sh

With OpenSSL 1.1.0, `s_client -no_ssl2` fails with an "unknown option" error. At the moment the `-no_ssl2` option is only used in two functions, `run_client_simulation()` and `run_crime()`. In `run_crime()`, the `-no_ssl2` option is only included if the OpenSSL version is 0.9.8.
This PR checks whether the OpenSSL version in use supports the `-no_ssl2` option, and if it doesn't, it removes it from the calls to `s_client` in `run_client_simulation()`.

OpenSSL 1.1.0 doesn't have "-no_ssl2" option

---

testssl.sh

If testssl.sh is called with `--devel 22` and the response from `sslv2_sockets()` is not 0, then `tls_sockets()` will be called, and the result of the `tls_sockets()` command will be output rather than the result of the `sslv2_sockets()` command.

Fix "--devel" with SSLv2

---

testssl.sh

When `certificate_info()` is given a certificate with a DH public key it displays something like:
```
Server key size              fixme:  dhKeyAgreement 3072 bits (FIXME: can't tell whether this is good or not)
```
This PR fixes that so that the output is:
```
Server key size              DH 3072 bits
```

Support DH server keys

---

testssl.sh

The test for whether a server only supports SSLv2 was broken, since `$OPTIMAL_PROTO` will be `-ssl2` whether SSLv2 is the only protocol that succeeds or no protocol succeeds.
This PR sets `$OPTIMAL_PROTO` (or `$STARTTLS_OPTIMAL_PROTO`) to "" if no protocol succeeds.

Fix SSLv2-only test in determine_optimal_proto()

---

testssl.sh

If the version of OpenSSL being used doesn't support `s_client -ssl3` (e.g., OpenSSL 1.1.0), `run_ssl_poodle()` displays "not vulnerable (OK)" even though it can't test whether the server is vulnerable.
This PR fixes it so that a "Local problem" warning is displayed if `s_client -ssl3` isn't supported.
The PR also removes the `$SNI` from the call to `$OPENSSL s_client`, since SSLv3 doesn't have SNI.

Warning on Poodle test when no local SSLv3 support

---

testssl.sh

This PR is in response to issue #454. I tried repeating the reported problem by creating a certificate in which the extendedKeyUsage extension was present and only included the anyExtendedKeyUsage OID. In running the test, I discovered two problems.
First, when `determine_trust()` is calling `verify_retcode_helper()` to display the reason that path validation failed, it assumes that there are at least two certificate bundles provided. (I was running the test using just one certificate bundle, containing my local root.) So, I changed `determine_trust()` to use `${verify_retcode[1]}` rather than `${verify_retcode[2]}` in the case that all bundles failed (it seems that 2 vs. 1 was an arbitrary choice).
Once that was fixed, testssl.sh output "NOT ok  (unknown, pls report) 26". So, the second …

Output correct error for unsupported certificate purpose

---

testssl.sh

Fix referenced but not assigned variable `sign_algo`.
```
In testssl.sh line 4309:
fileout "${json_prefix}algorithm" "DEBUG" "Signature Algorithm: $sign_algo"
^-- SC2154: sign_algo is referenced but not assigned.
```
Found by ShellCheck.

certificate_info(): Fix unassigned variable.

---

testssl.sh

The argument to -nextprotoneg is provided in sometimes empty an unquoted
variables. Because of the missing quotes, the next word on the line "-status"
gets parsed as "-nextprotoneg"'s argument instead of enabling the OCSP status
check.
This fixes #467.

quote argument for s_client's -nextprotoneg parameter

---

testssl.sh

- Fix two instances of referenced but not assigned variables.
- Fix a modified in subshell bug in `run_application_banner()`
- Fix indentation in `run_rp_banner()`

run_rp_banner(), run_application_banner(): Three issues

---

testssl.sh

do_rc4 is duplicated in debug_globals(), but this duplication is unnecessary.
Remove this duplication and make the list in debug_globals() consistent with the one in query_globals().

Remove duplicated do_rc4 in debug_globals()

---

testssl.sh

The mapping file is now only used in `show_rfc_style()`. This PR changes `show_rfc_style()` to use the `$TLS_CIPHER_HEXCODE` and `$TLS_CIPHER_RFC_NAME` arrays.
Note that `get_install_dir()` still searches for the mapping-rfc.txt file in order to determine `$INSTALL_DIR`. `$INSTALL_DIR` is only used to determine the location of the CA bundles in `determine_trust()`:
```
local ca_bundles="$INSTALL_DIR/etc/*.pem"
```

Don't use mapping-rfc.txt

---

testssl.sh

This PR adds the option for `parse_sslv2_serverhello()` to extract information from the ServerHello (server key size and cipher suites supported) and write the information to `$TMPFILE` as well as to write the server's certificate to `$HOSTCERT`.

Add option for extract data from SSLv2 ServerHello

---

testssl.sh

creation of ca_bundles fails in case the environment variable CA_BUNDLES_PATH has been set.

fix usage of CA_BUNDLES_PATH env for local ca_bundles

---

testssl.sh

Now that the mapping file is no longer used, `$ADD_RFC_STR` should not be unset just because the mapping file cannot be found.
In addition, since `show_rfc_style()` is now used in `parse_tls_serverhello()`, it cannot return an empty string just because the user set "--mapping no-rfc" on the command line. Instead, `neat_list()` should check the value of `$ADD_RFC_STR` and not call `show_rfc_style()` if it has been unset.
Finally, since `show_rfc_style()` no longer returns strings with extra spaces, there is no need to call `strip_spaces()`

Fix for when no mapping file is present

---

testssl.sh

I had the need to test for Apple ATS9 compatibility last week, and found that only SSLLabs had the option. This client simulation has been created using the cipher/protocol spec from SSLLabs and the handshake bytes for that spec from the bundled openssl.

Apple ATS9 client simulation

---

testssl.sh

This PR extended `parse_tls_serverhello()` in a few ways:
* If the "full" response is to be parsed, then additional checks are performed to verify that `$tls_hello_ascii` contains the entire response
* The extensions field is parsed and the list of extensions found is placed in `$TLS_EXTENSIONS` (if the "full" response is being parsed).
* Initial support for TLS 1.3 is added:
- Accounts for differences between TLS 1.2 ServerHello and TLS 1.3 ServerHello (as outlined in PR #499).
- Recognizes new alerts and handshake message types.
- Allows for server response to include message fragments of type "application data"

Extend TLS ServerHello parsing (part 1)

---

testssl.sh

This PR adds initial parsing of the ServerKeyExchange message to `parse_tls_serverhello()`. For ephemeral DH keys, it extracts the length of the key. For ephemeral ECDH keys that are encoded using the named_curve option, it extracts the length of the key and the name of the curve.

Extend TLS ServerHello parsing (part 2)

---

testssl.sh

This PR makes similar changes to `run_client_simulation()` as were made to `tls_sockets()`, so that  `run_client_simulation()` retrieves the entire server response, even if it is split across multiple packets, and it has `parse_tls_serverhello()` extract information about the server's ephemeral public key, if present.
The PR also changes `run_client_simulation()` to use information about the ephemeral public key. It includes the length of the public key in the output and, if it is a DH public key, checks that the size is within the acceptable range (`${minDhBits[i]} <= dh_bits <= ${maxDhBits[i]}`).

Use ephemeral public key in client simulations

---

testssl.sh

This PR uses `tls_sockets()` to determine whether a server supports certain extensions that may not be supported by `$OPENSSL`. At the moment it checks for max_fragment_length, client_certificate_url, truncated_hmac, ALPN, signed_certificate_timestamp, encrypt_then_mac, and extended_master_secret.
In https://github.com/dcooper16/testssl.sh/blob/extended_tls_sockets/testssl.sh, `run_server_defaults()` is re-written to use `tls_sockets()` instead of `$OPENSSL`, with just one call to `$OPENSSL s_client` to get the session ticket, which reduces the dependence on `$OPENSSL`, but this PR limits the number of calls to `tls_sockets()`, which is still slow.
Note: I included ALPN in the `tls_sockets()` ClientHello since a single call to `tls_sockets()` cannot test for both NPN and ALPN, and since …

Find more extensions in run_server_defaults()

---

testssl.sh

This PR adds parsing of the CertificateStatus message to `parse_tls_serverhello()`. If the caller requests that the "full" response be parsed, then the CertificateStatus message is parsed, and the OCSP response is added to `$TMPFILE`, in a manner similar to the output of `$OPENSSL s_client` when the `-status` option is used.

Extend TLS ServerHello parsing (part 4)

---

testssl.sh

The Apple ATS 9 iOS 9 client simulation test had an incorrect short name
which resulted in a duplicate ID in the JSON output

fix a duplicate test id in the client sim section

---

testssl.sh

The string "CamelliaGCM" is too long for the "Encryption" column printed by `neat_list()`. So, either "CamelliaGCM" needs to be shortened to "Camellia" (as this PR does), or the "Encryption" column needs to be made wider.

Fix neat_list() for Camellia GCM

---

testssl.sh

When `tls_sockets()` is used with the "full" option and the chosen cipher suite involves an ephemeral finite-field DH key (DH), this PR extracts the public key from the ServerKeyExchange message and adds it to `$TMPFILE`. In addition (and the primary reason for this PR), it compares the ephemeral public key's parameters to those specified in [RFC 7919](https://www.rfc-editor.org/rfc/rfc7919.txt), and indicates whether one the groups from that RFC was used. This will allow `run_pfs()` to be extended to indicate which, if any, [RFC 7919](https://www.rfc-editor.org/rfc/rfc7919.txt) DH groups a server supports.
This PR extracts the [RFC 7919](https://www.rfc-editor.org/rfc/rfc7919.txt) DH group parameters from the key pairs in `$TLS13_KEY_SHARES`. The primary purpose for `$TLS13_KEY_SHARES is …

Extend TLS ServerHello parsing (part 5)

---

testssl.sh

This PR extends `tls_sockets()` by parsing the contents of the ALPN and NPN extensions, if the "full" response is being processed.

Extend TLS ServerHello parsing (part 6)

---

testssl.sh

> The dh_bits are still not shown, maybe because of #531.
This PR fixes the issue of dh_bits not being shown if the cipher-mapping.txt file is missing. The problem is that the code in `parse_tls_serverhello()` that parses the ServerKeyExchange message assumes that `$rfc_cipher_suite` has the RFC version of the name the cipher suite. However, if the cipher-mapping.txt file is missing, `$rfc_cipher_suite` will have the OpenSSL name of the cipher suite. This PR changes the code to recognize either the RFC or OpenSSL names for ciphers with ephemeral DH or ECDH keys.

More fixes for missing cipher mapping file

---

testssl.sh

This function reorganizes `run_server_defaults()` based on the suggestion in #515.
The current `determine_tls_extensions()` is renamed to `get_server_certificate()`, and two changes are made to it:
* it no longer includes an extra call to `$OPENSSL s_client` to check for the ALPN extension; and
* rather than setting `$TLS_EXTENSIONS` to be the extensions found during this call to the function, it adds any newly found extensions to those already in `$TLS_EXTENSIONS`.
The PR then adds a new function, `determine_tls_extensions()`, which borrows some logic from the old `determine_tls_extensions()`, but this new `determine_tls_extensions()` only looks for additional TLS extensions, including ALPN.
`run_server_defaults()` makes multiple calls to `get_server_certificate()` (as it previously did …

Reorganize run_server_defaults()

---

testssl.sh

This PR fixes two minor bugs in run_allciphers():
* If `$SSL_NATIVE` or `$FAST` is `true`, then the cipher mapping file will not be used (unless `$OPENSSL ciphers` does not support the `-V` option), so there is no "fallback" to openssl, even if `[[ $TLS_NR_CIPHERS == 0 ]]`.
* If `$using_sockets` is `false` and `$SHOW_EACH_C` is `true`, then `ossl_supported` should be checked to see if the cipher was tested, not `TLS_CIPHER_OSSL_SUPPORTED`.

run_allciphers() bug fixes

---

testssl.sh

The current logic doesn’t work with some SMTP servers which are picky about protocol order, so I always had to go with `FAST_STARTTLS=false`. Additionally the current code already tries to work around some of the problems instead of just performing STARTTLS properly, which is actually not as hard as it seems – at least for the ftp, smtp, pop and imap, as well as the partially-supported nntp.
Still not converted to a proper STARTTLS dialog are partially-supported ldap and xmpp. ldap is a beast on its own, and xmpp requires XML parsing for compliance. I left them at the bad state for now.
It would be cool if openssl had support for picking up a live session in a fd, and starting TLS from where it was left. This way, testssl.sh could implement STARTTLS, and openssl could take over for …

Implement proper STARTTLS handshake for ftp, smtp, pop, imap and nntp

---

testssl.sh

The `fixmeln()` function was misnamed `fixme()`.

Typo in definition of fixmeln()

---

testssl.sh

When the cipher-mapping.txt file is read, the contents of the "Mac=..." column is placed in `TLS_CIPHER_EXPORT` rather than the contents of the "export" column. This PR fixes that.

Fix bug in reading of cipher mapping file

---

testssl.sh

This PR implements `run_rc4()` in a similar manner to `run_allciphers()` and `run_cipher_per_proto()` (in PR #541). The change doesn't seem to have much of an impact on speed, but when sockets are used it can detect ciphers that aren't locally supported by OpenSSL.

run_rc4() sockets implementation

---

testssl.sh

The Postgres protocol uses STARTTLS with a custom start packet. This
functionality is supported by openssl s_client in the current openssl
master branch but not yet in any released version.
This patch detects whether the given openssl binary supports postgres
and runs the default tests against a postgres server.
Example of no openssl support:
~/bin/testssl$ ./testssl.sh --quiet
--openssl=/opt/openssl/openssl-1.1.0c/bin/openssl --starttls=postgres
test.postgres.server.com:5432
Start 2016-12-07 18:03:24    -->> ip.add.re.ss:5432
(test.postgres.server.com:5432) <<--
Fatal error: Your /opt/openssl/openssl-1.1.0c/bin/openssl does not
support the "-starttls postgres" option
Example of openssl support:
~/bin/testssl$ ./testssl.sh --quiet
--openssl=/opt/openssl/openssl-2016-12-07/bin/openssl …

Add support for testing postgres protocol over TLS/SSL

---

testssl.sh

This PR is a proposed alternative to #537. It only attempts to extract the certificate and list of ciphers from the SSLv2 ServerHello is `ret=3`.

Don't parse SSLv2 ServerHello unless successful response

---

testssl.sh

For several elliptic curves the number of bits, as indicated by OpenSSL, is slightly different than the name implies. For example, for sect239k1 OpenSSL outputs: `Server Temp Key: ECDH, sect239k1, 238 bits`.
This PR aligns the output created by `parse_tls_serverhello()` with OpenSSL.

Align elliptic curve lengths with OpenSSL

---

testssl.sh

Hi,
To avoid escape characters in json and csv reports i would suggest to set COLOR to zero by default for these formats.
**JSON with escape charachters:**
```
"id"           : "cipher_xc030",
"severity"     : "INFO",
"finding"      : "xc030   ECDHE-RSA-AES256-GCM-SHA384       ECDH [0;32m571 [m  AESGCM    256      TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
},{
"id"           : "cipher_xc028",
"severity"     : "INFO",
"finding"      : "xc028   ECDHE-RSA-AES256-SHA384           ECDH [0;32m571 [m  AES       256      TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384"
},{
```
**CSV with escape charachters:**
```
"cipher_xc030","xxx","INFO","xc030 ECDHE-RSA-AES256-GCM-SHA384 ECDH [0;32m570 [m AESGCM 256 TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384","","",""
"cipher_xc028","xxx","INFO","xc028 …
```

Avoidance of escape characters in JSON and CSV reports

---

testssl.sh

When `test_just_one()` uses `neat_list()` with a cipher that is not available and that uses DH for key exchange, the columns do not line up correctly. `test_just_one()` adds "TBD" in gray to "DH", and while `neat_list()` tries to adjust for the presence of color codes, it doesn't seem to correctly handle the gray color code here.
Rather than try to fix this in `neat_list()`, I propose to just remove the "TBD". Adding it is inconsistent with other functions (like `run_allciphers()`), and it seems inappropriate, since there is nothing "to be determined," as the cipher suite isn't supported by the server.
If adding "TBD" were appropriate anywhere, it would seem to be in cases in which the server does support the cipher, but the number of bits in the ephemeral key couldn't be determined …

Fix alignment problem in test_just_one()

---

testssl.sh

In a few places testssl.sh tries to determine $OPENSSL s_client's capabilities by calling `$OPENSSL s_client` without specifying a host to which to connect. For example:
```
$OPENSSL s_client -no_ssl2 2>&1
```
This idea is that `$OPENSSL s_client` should reveal something about its capabilities without actually trying to connect to a host.
This works in most cases. However, the manual pages for s_client states:
```
-connect host:port
This specifies the host and optional port to connect to. If not specified then an attempt is made to connect to the local host on port 4433.
```
So, the above call is actually trying to connect to the local host on port 4433. If the local host is running `$OPENSSL s_server`, then `$OPENSSL s_server` will by default be listening on port 4433, and the connection …

testssl.sh hangs on local testing

---

testssl.sh

This PR adds ",exp" to the bits column when `run_rc4()` is run in the "--wide" mode and the cipher is an export cipher. This makes the wide mode of `run_rc4()` align with other functions, such as `run_allciphers()`.

Mark export ciphers in run_rc4()

---

testssl.sh

This PR changes `run_http2()` so that it uses `tls_sockets()` rather than failing, if `$OPENSSL` does not support the `-alpn` option. If `$OPENSSL` supports the `-alpn` option (or if `$SSL_NATIVE` is true), then this PR has no effect.

Use sockets for run_http2()

---

testssl.sh

In a few places `run_protocols()` specifies the wrong TLS version as the "ID" when calling `fileout()`.

Minor bug fixes in run_protocols()

---

testssl.sh

This PR implements `run_pfs()` in a manner similar to `run_allciphers()`. It uses OpenSSL followed by `tls_sockets()` to test for both supported PFS cipher suites as well as elliptic curves offered.
I made an attempt at addressing #548 by using different colors to print the different curve names, depending on strength. The colors chosen are exactly the same as those that would be chosen by `read_dhbits_from_file()`:
```
163 < # bits <= 193: pr_svrty_minor
193 < # bits <= 224: out
```
I also added code for #464 to create a list of the DH groups from RFC 7919 that a server supports. However, since no servers seem to support this at the moment (except with TLS 1.3), I marked this code to only run if the $EXPERIMENTAL flag is set.

run_pfs() speedup + sockets

---

testssl.sh

I have a symlink to testssl.sh in /usr/local/bin/testssl so I can run it outside the git repository.  With the latest pull from the 2.9dev branch I wasn't able to do that anymore.  This works without having realpath installed.  I also removed trailing whitespace since that is a pet peeve of mine.

Detect $TESTSSL_INSTALL_DIR when testssl is a symlinked command

---

testssl.sh

This PR fixes a few bugs in `sslv2_sockets()`. The main issue is that a server may not send the entire ServerHello in a single packet. If it doesn't and the full response is being parsed (i.e., certificate and list of ciphers), then `parse_sslv2_serverhello()` will encounter errors, since it assumes that it has the entire ServerHello. This PR compares the length of the response to the length of the ServerHello as specified in the first two bytes of the response and requests more data from the server if the response appears incomplete.
This PR also modifies `parse_sslv2_serverhello()` to check for more errors. It compares the length of the response it has been provided to the specified length (`$v2_hello_length`) and returns an error if the response is shorter than `$v2_hello_length` and …

sslv2_sockets() bug fixes

---

testssl.sh

If `determine_tls_extensions()` does not create a temporary file (`$TEMPDIR/$NODEIP.determine_tls_extensions.txt`) then `run_server_defaults()` will display error messages when an attempt is made to copy this file or to search (grep) it. This may happen if `$OPTIMAL_PROTO` is `-ssl2` or if `determine_tls_extensions()` uses sockets and `parse_tls_serverhello()` encountered an error and did not create a temporary file (`$TEMPDIR/$NODEIP.parse_tls_serverhello.txt`). This PR fixes this by only trying to copy and search `$TEMPDIR/$NODEIP.determine_tls_extensions.txt` if `$OPTIMAL_PROTO` is not `-ssl2` and `determine_tls_extensions()` was successful (return value 0).

run_server_defaults() bugfix

---

testssl.sh

There are two places in `run_client_simulation()` in which `$OPENSSL s_client` is called, after which there is a `debugme echo` line to display the `$OPENSSL s_client` command line when testssl.sh is being run in debug mode, and then `sclient_connect_successful $? $TMPFILE` is called to determine whether `$OPENSSL s_client` successfully established a connection.
So, `sclient_connect_successful()` is being passed the result of the `debugme()` call, which always returns 0, rather than the result of the `$OPENSSL s_client` call.
This PR fixes the problem by moving the `debugme()` line to before the call to `$OPENSSL s_client`, so that  `sclient_connect_successful()` is passed the results of the `$OPENSSL s_client` call.

run_client_simulation() bugfix

---

utils/generate_static_cipher_lists.sh

This PR adds a new utility that generates the various static cipher lists that appear in testssl.sh.
This utility serves two purposes:
* It can be run whenever new ciphers are added to cipher-mapping.txt to see if any of the lists in testssl.sh need to be updated. (This includes if cipher-mapping.txt is modified to add OpenSSL-style names for ciphers that are currently listed, but that have not yet been assigned such names.)
* The source code can be used as a reference in order to understand how each of the lists is defined.

Create static cipher lists for testssl.sh

---

testssl.sh

This PR changes `run_std_cipherlists()` to use sockets. As noted in isse #554, I have some questions about the definitions of the cipher lists, but I wrote the code so that the ciphers that are tested when using sockets are the same as those that are tested when using OpenSSL. For a few of the cipherlists, the sockets version tests a few additional ciphers; but these are ciphers that are not supported by OpenSSL, and whose definitions are consistent with the ciphers that OpenSSL includes.
As written, `std_cipherlists()` will use sockets for testing by default, except in two cases:
* If the `$SSL_NATIVE` is true, then only OpenSSL is used, and if OpenSSL doesn't support any ciphers in the cipherlist, then a "Local Problem" warning is displayed.
* If `$FAST` is true (but `$SSL_NATIVE` is …

Use sockets for run_std_cipherlists()

---

testssl.sh

In some cases, the "TLS extensions" line output for the "--server-defaults" option will not show `"encrypt-then-mac/#22"` even if the server supports this extension. The reason is that a server will only include this extension in the ServerHello message if it supports the extension and the selected cipher is a CBC cipher. So, if `determine_tls_extensions()` connects to the server with a non-CBC cipher, then it will not detect if the server supports the encrypt-then-mac extension.
It is possible that support for the extension will be detected by `get_server_certificate()`, but only if one of the calls to that function results in a CBC cipher being selected and OpenSSL 1.1.0 is being used (as prior versions did not support the encrypt-then-mac extension).
In this PR, if …

 Detect support for encrypt-then-mac extension

---

testssl.sh

This PR changes `run_crime()` to use `tls_sockets()` rather than failing if `$OPENSSL` lacks zlib support, unless `$SSL_NATIVE` is `true`.
At the moment, the ClientHello created by `socksend_tls_clienthello()` only specifies the NULL compression method. So, this PR adds a new parameter to `socksend_tls_clienthello()` and `tls_sockets()` to allow the caller to request that additional compression methods (DEFLATE and LZS) be specified in the ClientHello.
This PR makes another change to `run_crime()`. At the moment, if `$OPENSSL s_client` fails to connect to the server, `run_crime()` will report that the server is not vulnerable, since the output from `$OPENSSL s_client` includes the line "Compression: NONE" (see below). This PR changes that by checking whether the connection was successful, …

Use sockets for run_crime()

---

testssl.sh

Hi @drwetter ,
In response to your request in #572, this PR provides a starting point for addressing #120. It adds code to `run_logjam()` to try connecting to the server using any cipher that uses an ephemeral DH key. If successful, it gets the server's ephemeral key (in OpenSSL's PEM format) and then extracts the prime from the key and places it in `$dh_p`. So, all that needs to be done at this point is to compare `$dh_p` against a set of "bad" primes. I'm not sure if I'll be able to work on that part soon, so if someone else has the time, that would be great.
I actually found the `-msg` option easy to use. I moved the code in `parse_tls_serverhello()` that extracts the DH ephemeral public key from the ServerKeyExchange message into a separate function. Then, if using OpenSSL with the …

Extend logjam phase 1

---

utils/generate_static_cipher_lists.sh

This PR adds a function that generates a list of all DHE ciphers for `run_logjam()`.

Generate list of all DHE ciphers

---

testssl.sh

This PR just fixes a minor bug in `tls_sockets()`, changing
```
debugme "stuck on sending: $ret"
```
to
```
debugme echo "stuck on sending: $ret"
```

Fix typo in tls_sockets()

---

testssl.sh

This PR changes testssl.sh so that when ciphers are being listed in wide mode (i.e., using `neat_list()`) and the `--show-each` option is set, ciphers that are not available are printed in light grey, whereas ciphers that are available continue to be printed in black. This makes it easier to distinguish between ciphers that are available and those that are not (the "available/"not a/v" column remains).
This PR does not change the way that ciphers that are available are printed, but it includes a hook that would allow that to change. For example, for ciphers that are available, the name of the cipher suite could be printed in a different color depending on its quality (as is done for the "Negotiated cipher" in `run_server_preference()`). The same could be done for the "Encryption" and …

Print unsupported ciphers in light grey

---

testssl.sh

In the revised code that was created to address #587, nothing is printed after "OCSP URI" if there is neither an OCSP URI nor a CRL URI. Instead, "--" should be printed (perhaps it should be printed in red, just as the "--" for the CRL is).
I still believe that there is an inconsistency in the reporting of the output, however. At the moment, the "Certificate Revocation List" and "OCSP URI" lines indicate it is acceptable as long as the certificate contains either a CRL URI or an OCSP URI. However, the "OCSP stapling" line reports a minor finding if an OCSP response was not included in the server's reply. Shouldn't we just assume that if the certificate doesn't include an OCSP URI, then it wouldn't be possible for the server to obtain an OCSP response to staple to its reply? If so, then it …

Update fix to 587

---

utils/generate_static_cipher_lists.sh

This PR renames the cipher lists for `run_logjam()` in generate_static_cipher_lists.sh to align with their names in testssl.sh, as requested in #590.
I think these names are still open for misinterpretation, however, since its not clear whether "dh_cipher" refers to ciphers that use static DH keys, ephemeral DH keys, or both.

Rename cipher lists for run_logjam()

---

testssl.sh

[RFC 4492](https://www.rfc-editor.org/rfc/rfc4492.txt) introduced the Supported Elliptic Curves Extension, but this extension was renamed Supported Groups in [RFC 7919](https://www.rfc-editor.org/rfc/rfc7919.txt). Following [RFC 7919](https://www.rfc-editor.org/rfc/rfc7919.txt) (and [TLSv1.3](https://www.ietf.org/id/draft-ietf-tls-tls13-18.txt)), `parse_tls_serverhello()` refers to this extension as "supported groups/#10". Since, at the moment, OpenSSL's s_client refers to this extension as "elliptic curves/#10", the extension sometimes appears twice in the "TLS extensions" line, if it is detected by both OpenSSL (in `get_server_certificate()`) and `tls_sockets()` (in `determine_tls_extensions()`):
```
TLS extensions (standard)    "renegotiation info/#65281" "elliptic curves/#10" "EC …
```

Handle renaming of the Supported Elliptic Curves Extension

---

testssl.sh

This is an attempt to force the use of the system binaries for OpenSSL if on WSL.  (See #605)
The evil thing is, this (testssl.sh) is *slow* on WSL.  Not sure why, but it is...

Attempt to force system binaries for WSL

---

testssl.sh

This PR addresses the issue raised in #623. This PR is based on the function `out_row_aligned_max_width()` that I proposed in #623, but the `out_row_aligned_max_width()` in this PR is a little different. It takes a fourth parameter, which is the function to use to print each word in the text string to be printed. This is used in `run_pfs()` so that the "Elliptic curves offered" can be printed using this function (some servers support 25 curves), while still having the curves printed using color-coding to indicate the quality of each curve.
I somewhat arbitrarily have each line wrap at 120 characters, but that could be changed (e.g., to `$TERM_WIDTH`).

Wrap long lines

---

testssl.sh

When a list of cipher suites is being displayed using `neat_list()`, testssl.sh shows the cipher suite's OpenSSL name and (in most cases) the RFC name as well. However, in all other cases only the OpenSSL name is shown.
This PR adds the option to have cipher suite's RFC names shown instead of the OpenSSL name, by including `--mapping rfc` in the command line. [Note: if the cipher-mapping.txt file cannot be found, then the `--mapping rfc` option is ignored and the OpenSSL names are shown.]
This PR seems to be related to issue #9, but #9 may be been referring to the output created by `neat_list()`.

Option to show RFC cipher names

---

testssl.sh

Since the test for TLS 1.2 in `run_protocols()` now uses `tls_sockets()` whenever `$ssl_native` is `true` (i.e., there is no longer a requirement for `$EXPERIMENTAL` to be true as well), the `$EXPERIMENTAL` flag should no longer be checked if the return value is 1.

run_protocols() bug fix

---

testssl.sh

[RFC 7633](https://tools.ietf.org/html/rfc7633) introduces the TLS Features certificate extension, which contains "Features":
> The object member "Features" is a sequence of TLS extension identifiers (features, in this specification's terminology) as specified in the IANA Transport Layer Security (TLS) Extensions registry.  If these features are requested by the client in its ClientHello message, then the server MUST return a ServerHello message that satisfies this request.
The main purpose of this certificate extension is to implement "must staple." If the extension is present in a TLS server's certificate and it includes status_request, then the server MUST include a stapled OCSP response if the client requests one. (The same applies for the status_request_v2 extension.)
This PR adds a …

OCSP must staple

---

testssl.sh

It seems that the head command on OS X does not accept a negative number as a value for the "-n" parameter. This PR provides an alternative method for removing the "generator:  " line without using "head."

Fix issue #643

---

testssl.sh

Some sites have a long list of IP addresses and some IP addresses have a long list of DNS names that map to them.
This PR changes `display_rdns_etc()` to use `out_row_aligned_max_width()` to print the other IP addresses in `$IP46ADDRs` and to print `$rDNS`.

Wrap long lines in display_rdns_etc()

---

testssl.sh

With the latest pull, I kept getting a `tr` error when I ran testssl.sh:
`$ ./testssl.sh -q -U google.com
tr: extra operand ‘1.0.2-chacha’
Only one string may be given when deleting without squeezing repeats.
Try 'tr --help' for more information.`
I tracked it down to a missing `<<<` in the `find_openssl_binary` function.
I also removed trailing whitespace since that is a pet peeve of mine.

Add missing herestring redirect (<<<) in find_openssl_binary function

---

testssl.sh

This PR attempts to address #631. It allows four choices for the `--mapping` option. "openssl" (default), "rfc", "no-openssl", and "no-rfc".
* "openssl" is the current default
* "no-rfc" shows only the OpenSSL names (just as it currently does)
* "rfc" shows the RFC name rather than the OpenSSL name for things that are not in wide now (just as it currently does). But now, in wide mode, it shows the RFC name first (further to the left) and the OpenSSL name second.
* "rfc-only" shows only the RFC name.
If the `--mapping` option is not provided, this is the same as "openssl". If the "cipher-mapping.txt" file cannot be found, then testssl.sh runs as if "no-rfc" had been requested.

Add option to print only the RFC cipher names

---

testssl.sh

So far I haven't seen any HTML reserved characters (&, <, >, ", ') in the strings processed by `emphasize_stuff_in_headers()`, so this PR may be unnecessary. However, this PR will ensure that any such characters will be properly escaped in the HTML output.

 Handle HTML reserved characters in headers

---

testssl.sh

When I view testssl.sh in KDE's text editor (kate), the code after the "INFO" line in `show_finding()` isn't highlighted correctly, and the highlighting doesn't correct again until `pr_liteblueln()`. This PR fixes the highlighting issue by adding spaces between "]]" and ")". To be "safe," I also added spaces between "(" and "[[", and similarly added spaces in `is_json_format()`.

Add spaces in show_finding()

---

testssl.sh

While doing some performance testing I discovered that `normalize_ciphercode()` is very slow. This PR simplifies the function and speeds it up significantly. This PR also addresses the TODO item in `normalize_ciphercode()` by eliminating the global variable HEXC.

Speedup normalize_ciphercode()

---

testssl.sh

Currently there is code to extract TLS extensions in three places, in `get_server_certificate()` and two places in `determine_tls_extensions()`. This PR replaces them with one new function, `extract_new_tls_extensions()`.
In order for the new function to work correctly whether OpenSSL or `tls_sockets()` is being used, this PR also changes `parse_tls_serverhello()` so that extensions are formatted in the file it creates in the same way as they are formatted by OpenSSL.

Cleanup extraction of TLS extensions

---

testssl.sh

This PR fixes two minor bugs:
* In `run_hpkp()`, the call to `$OPENSSL s_client` includes the option `-showcerts` twice. This PR removes one of them.
* In `get_server_certificate()`, the first call to `$OPENSSL s_client` includes `$addcmd`, but `$addcmd` has not yet been initialized. Instead, `$SNI` should be used.

Fix two minor bugs

---

testssl.sh

In `create_client_simulation_tls_clienthello()` the variable `sni_extension_found` should be set if the ClientHello includes an SNI extension. Instead it was being set if and only if the ClientHello included some extension other than SNI.
This bug wasn't detected before for two reasons:
* It is rare to have a ClientHello that includes an SNI extension, but no other extensions.
* The code still works correctly if `sni_extension_found` is set even if there is no SNI in the ClientHello.
So, the bug only creates a problem if the browser's ClientHello include an SNI extension and no other extensions (see "BingPreview Jun 2014" in the client_simulation branch).

Fix client simulation

---

testssl.sh

`std_cipherlists()` does not include line breaks between tests in the output to the terminal when `$DEBUG` is 1, and it does not include line breaks between tests in the HTML output whenever `$DEBUG` is greater than 0.

Fix std_cipherlists with debug

---

testssl.sh

With the commit made on March 26, "partly (1/2) fixing #653," an HTML banner isn't added to the HTML files anymore.  A banner should be added to the top of the HTML file if mass testing is being performed and a separate HTML file is being created for each test.
The `$APPEND` flag being `true` is an indicator that mass testing is being performed and that this is one of the individual tests being run. Given that `$APPEND` is `true`, `$HTMLHEADER` being `true` indicates that testssl.sh is creating the file name for the HTML output. So, it is when both flags are `true` that the HTML banner should be created.

Missing HTML banner

---

t/01_badssl.com.t
t/100_report_structure.t
t/11_hpkp.t
testssl.sh

This PR introduces the environment variable `CHILD_MASS_TESTING` (see #684), and uses it as an indicator that testssl.sh is running as a child within mass testing rather than using the `$APPEND` flag. It also makes a number of other changes to make the handling, of HTML, CSV, JSON, and log files consistent, and it fixes a number of bugs related to the generation of these files when mass testing is being performed.
Please let me know if you disagree with any of the changes in this PR, or if you would prefer that it be broken up into multiple smaller PRs.
Some of the changes are as follows:
- When the `$APPEND` flag is true, all of these files are appended to and headers and footers are omitted. (Perhaps this should be changed. Appending to a log file isn't an issue, but appending to a JSON …

Child mass testing env variable

---

testssl.sh

In `run_server_defaults()` the variable `success` is defined twice, once an an ordinary variable and once as an array. The PR removes the incorrect definition. It also removes the definitions of some variables that are no longer used and reorganizes the definitions so that each line has only one variable type.
I also noticed a typo later in `run_server_defaults()` and corrected it.
I also corrected the indentation in `run_server_defaults()`.

Cleanup variable definitions in run_server_defaults()

---

testssl.sh

This PR fixes a problem that occurs if log file names include spaces.

Handle word splitting of log file names.

---

testssl.sh

I was doing some testing on my extended_tls_sockets branch and discovered that it was not fully working since the `TLS13_KEY_SHARES` array was empty. According to https://lists.gnu.org/archive/html/bug-bash/2012-06/msg00068.html, there is an issue when trying to initialize a global array inside a function. (The current code initializes `TLS12_CIPHER`, `TLS_CIPHER`, and `TLS13_KEY_SHARES` within `get_install_dir()`, since tls_data.txt is read in that function.) In fact, according to http://stackoverflow.com/questions/10806357/associative-arrays-are-local-by-default, in order to initialize a global variable in a function, one needs to provide the `-g` option, which was only added in Bash 4.2.
This PR seems to fix the problem by moving the reading of tls_data.txt to the main body of the code …

Don't read tls_data.txt inside function

---

testssl.sh

This PR just addresses some places where quotes need to be used to avoid word splitting in case the referenced file, or path to the file, contains space characters.

More fixes for #702

---

testssl.sh

`emphasize_stuff_in_headers()` only adds color to the text being printed to the terminal if `$COLOR` is 2. So, the same should be the case for the HTML output.

Use of color in emphasize_stuff_in_headers()

---

testssl.sh

This PR fixes two places in which output is being included in the HTML output, but shouldn't be.

No debugging text in HTML output

---

t/02_http.t

I've never programmed in perl before, but this script seems to work. It includes two checks:
* I runs testssl.sh without the `--debug` flags and checks that the HTML file is the same as what is sent to the terminal.
* It runs testssl.sh with `--debug 4` and checks that the HTML file created is the same as the one created without the `--debug` flag.
This PR is based on the request in #692.

Add Travis test for HTML output

---

testssl.sh

find_openssl_binary() should use $TESTSSL_INSTALL_DIR instead of $RUN_DIR once get_install_dir() has discovered it, especially since $TESTSSL_INSTALL_DIR is set to $RUN_DIR if it is correct.
I have a symlink in /usr/local/bin pointing to testssl.sh so I can run it from anywhere. Before making this change, it was looking for openssl in /usr/local/bin, failing, using the default system openssl, and complaining about GOST support.

Use $TESTSSL_INSTALL_DIR instead of $RUN_DIR in find_openssl_binary() - Second Try

---

testssl.sh

`$OPENSSL_LOCATION` is used in `fileout_pretty_json_banner()`, `html_banner()`, `mybanner()`, and `prepare_logging()`, but the value of `$OPENSSL_LOCATION` is populated in `mybanner()`. This is usually okay, since `mybanner()` is always called before the other three functions are called. However, if `$QUIET` is `true`, then `mybanner()` returns immediately, without populating `$OPENSSL_LOCATION`, even though the value of `$OPENSSL_LOCATION` may be needed by one or more of the other functions.
This PR addresses this problem by populating `$OPENSSL_LOCATION` in `find_openssl_binary()` rather than `mybanner()`.

Populate OPENSSL_LOCATION in find_openssl_binary

---

testssl.sh

`prln()` doesn't exist, it looks like it should be `outln()`.

Fix prln usage to outln

---

testssl.sh

$? has an exitcode of the previous if then fi statement, and because of that it's always 0; we need to use exit $ret here to correctly pickup what returned by `lets_roll` function.
It seems like an relict of `main()` function that existed before to me.

Use exit $ret at the end of the script

---

testssl.sh

When the `--log`, `--logging`, or `--logfile <logfile>` option is being used and testssl.sh is stopped, a "printf: write error: Broken pipe" message tends to appear (at least on my Linux desktop). From what I can tell, this is a result of the `tee` process being killed before the `cleanup ()` function completes. At the moment, `cleanup ()` doesn't write very much to `stdout`, but if parallel mass testing is performed, then `cleanup ()` may try to write the results of several previously completed tests.
This PR fixes the problem by adding the `-i` option ("ignore interrupt signals") to `tee`.
Note that I have tested this on a Linux desktop and an OS X laptop and it seems to work OK on both, but don't have a MS Windows computer on which to test this change.

Prevent broken pipe error

---

testssl.sh

This PR implements the suggestion from #753 for a child process in mass testing to send a signal to the parent to exit if the child encounters an error parsing its command line. At the moment, the child only sends the signal if it encounters an error that results in the `help()` function being called, but that could easily be changed (e.g., to also send a signal if `fatal()` is called in the child process).
In the case of parallel mass testing, the cleanup function needs to call `get_next_message_testing_parallel_result()` for the child that sent the signal, since otherwise the child's error message would not be displayed. Since I cannot tell which child sent the signal, I just call `cleanup()`, which displays the output of all completed child processes. Since the child process will send …

Stop parent if child encounters parsing error

---

testssl.sh

openssl/master branch now supports mysql STARTTLS in s_client
This patch adds support to call and use that s_client support to run
most, but not all (pfs, client simulation) tests.
The socket implementation is stubbed, but not yet functional.
----
@petermosmans: you'll need to pull the following 2 patches:
https://github.com/openssl/openssl/commit/a2d9cfbac5d87b03496d62079aef01c601193b58
https://github.com/openssl/openssl/commit/8530039a307f7aa8acb0516fdd38191baa91d434
----
@drwetter I've got a follow-up patch stack adding socket support, but since MySQL Community Edition uses yaSSL instead of OpenSSL, I'm finding a lot of small client/server compatibility issues. I'm working through them one by one, but wanted to get the s_client version to you first, as it's useful by itself.

Add mysql (openssl) starttls support

---

testssl.sh

In `run_hpkp()` there is a call to `$OPENSSL s_client` that uses `${sni[i]}` as one of the command line options, but `sni` is not defined. My guess is that this was a copy/paste error from `run_client_simulation()`, which is the only function where an `sni` array is defined.
I am guessing that the intention was to use `$SNI` in `run_hpkp()`.

run_hpkp() bug fix

---

testssl.sh

Following up on PR #774, here's the simple socket implementation of MySQL STARTTLS.
With this addition, several new tests will run against MySQL. However, there are still some bugs being worked out against the Community Edition (yaSSL), which are being addressed in PR #782.

Add mysql (sockets) starttls support

---

testssl.sh

A [commit](https://github.com/drwetter/testssl.sh/commit/e8b5a82c7e9c082396e2d016b870d4beae352427) that was made on May 15 replaced a `tm_out` with `echo` rather than `echo -n` resulting in an extra line break.

Remove extra line break in debugging output

---

testssl.sh

As reported in #782, some servers will return a ServerHello with a cipher not listed in the ClientHello rather than than return an Alert, if the server does not support any of the ciphers listed in the ClientHello.
This PR modifies `tls_sockets()` to check whether the cipher in the ServerHello was one included in the ClientHello and to fail if it wasn't.
@sdann : Could you try this out on your yaSSL to verify that it addresses the problem.

Handle server returning unsupported cipher

---

testssl.sh

Another yaSSL server incompatibility. MySQL protects against CCS
Injection by erroring if it sees two CCS requests before the handshake
completes. But instead of returning a TLS alert, it seems to error up
the stack to MySQL which returns its own error message.
Debug output looks like:
```
sending client hello,
reading server hello
1st reply:
sending payload #2 with TLS version x03, x02:
tls_content_type: 16 | tls_protocol: 0000 | byte6: 04
2nd reply:
00000000  16 00 00 02 ff 13 04 23  30 38 53 30 31 42 61 64  |.......#08S01Bad|
00000010  20 68 61 6e 64 73 68 61  6b 65                    | handshake|
0000001a
test failed, probably read buffer too small (16000002FF1304)
```
This patch adds a custom check for this MySQL specific error, as far
down in the error check path as I can.

Fix CCS Injection detection for MySQL (yaSSL)

---

testssl.sh

This PR adds the same additional check to `client_simulation_sockets()` as was previously added to `tls_sockets()`. It extracts the list of cipher suites offered from each ClientHello and passes the list to `parse_tls_serverhello()` so that `parse_tls_serverhello()` can check that the cipher offered in the ServerHello was included in the ClientHello.
This assumes that a real client would abort the connection if it was presented with a cipher in the ServerHello that it didn't offer in its ClientHello.

yaSSL and client simulation

---

testssl.sh

If $PROTOS_OFFERED was empty, and thus the protocols unknown, this
function would return true for any protocol you passed it. This caused
most callers to assume TLS1.0, even if the server didn't offer it.
Instead return false and make the caller do an extra lookup.

Fix logic in has_server_protocol()

---

testssl.sh

`std_cipherlists()` uses `has_server_protocol()` to determine whether to test for ciphers using SSLv2. However, this was resulting in false negatives due to #759. This PR removes the `has_server_protocol()` check so that SSLv2 is checked whenever the connection attempt with the TLSv1.2 ClientHello failed.

std_cipherlists() and has_server_protocol()

---

testssl.sh

This PR fixes the extraction of the cipher suites in SSLv2 ClientHellos in `client_simulation_sockets()`. Since `client_simulation_sockets()` can only handle SSLv3 and above ServerHellos, it removes any SSLv2 ciphers and converts the other cipher from 3-byte format to 2-byte format.

Fix client simulations with SSLv2 ClientHello

---

testssl.sh

The data for `run_client_simulation()` currently includes two clients that send version 2.0 CLIENT-HELLO messages (see Appendix E.2 of RFC 5246). Each of the CLIENT-HELLO messages advertises support for newer protocol versions (SSLv3 in the case of IE6XP and TLSv1.0 in the case of Java 6u45). A server may reject one of these version 2.0 CLIENT-HELLO messages, or it may respond with an SSLv2, SSLv3, or TLSv1.0 ServerHello.
The current code in `client_simulation_sockets()` assumes that the server's response with be an SSLv3 or later ServerHello. So, it can support cases in which servers respond with an SSLv3 or TLSv1.0 ServerHello (once PR #800 is accepted to undo the mistake in PR #797), but not cases in which servers response with an SSLv2 ServerHello.
This PR adds code to …

Client simulation and SSLv2 servers

---

testssl.sh

Currently, when `$DEBUG` is 2 and the connection is successful, `parse_tls_serverhello()` prints out information about the server's ephermal (EC)DH key, but nothing else. For example:
```
sending client hello... reading server hello...
dh_bits:                ECDH, P-256, 256 bits
sending close_notify...
(95 lines returned)
```
This PR changes `parse_tls_serverhello()` so that information about dh_bits is only displayed if `$DEBUG` is at least 3, making it the same as for other information about the server's response.
In addition, it indents the printing of the information about dh_bits in order to better align with other information displayed at  this debug level.

parse_tls_serverhello(), dh_bits, debug level 2

---

testssl.sh

testssl.sh produces an invalid JSON file if the `--json-pretty` option is used with the `--single-cipher` option. The reason is that `fileout_section_header()` isn't called before `run_cipher_match()` calls `fileout()` and `fileout_section_footer()` is not called afterwards.
There is also a problem with MEASURE_TIME, since the "cleanup" at the end of `lets_roll()` is not performed.
This PR fixes these problems by adding a call to `fileout_section_header()` before the call to `run_cipher_match()` and by copying the code from the end of `lets_roll()` to `run_cipher_match()` (just before the call to `exit`).

Fix single cipher and JSON pretty

---

testssl.sh

This PR addresses the same issue as https://github.com/drwetter/testssl.sh/commit/6bb3494d9807991fd07b8ca0e120b218a0318dfd.  In its current form, `fileout_insert_warning()` cannot be used after `fileout_section_header()` has been called for the first time.

Use of fileout_insert_warning()

---

etc/cipher-mapping.txt

A PR was just accepted into the master branch of https://github.com/openssl/openssl that specifies OpenSSL names for the ARIA GCM cipher suites: https://github.com/openssl/openssl/commit/bc32673869842c7f00ae7016040a612f516ead7e. This PR adds these OpenSSL names to the cipher-mapping.txt file. It also changes the description of the encryption algorithm for these ciphers from "ARIA" to "ARIAGCM" to be consistent with OpenSSL and with the other GCM ciphers in the cipher-mapping.txt file.
In addition, OpenSSL names for some of the ARIA CBC ciphers are provided in https://github.com/openssl/openssl/blob/master/doc/man1/ciphers.pod, and this PR adds those OpenSSL names to the cipher-mapping.txt file as well.

Add OpenSSL names for ARIA ciphers

---

testssl.sh

Unfortunately, most categories were passing incorrectly, since a
`tls_socket()` error was interpreted as a success for many of the cases.
Now we explicitly check for the known yaSSL failure and raise a warning
that the test is inconclusive.
New output against --starttls=mysql looks like:
```
Testing ~standard cipher categories
-----------------------------------
NULL ciphers (no encryption)                  SERVER_ERROR: test inconclusive due to MySQL Community Edition (yaSSL) bug.
Anonymous NULL Ciphers (no authentication)    SERVER_ERROR: test inconclusive due to MySQL Community Edition (yaSSL) bug.
Export ciphers (w/o ADH+NULL)                 SERVER_ERROR: test inconclusive due to MySQL Community Edition (yaSSL) bug.
LOW: 64 Bit + DES encryption (w/o export)     offered (NOT ok)
Weak …
```

Catch MySQL (yaSSL) server bug when testing standard cipher categories

---

testssl.sh

In case of an insecure redirect a duplicate finding would be logged.
First finding would be HTTP_STATUS_CODE with severity HIGH and content ','.
Second finding would be HTTP_STATUS_CODE with severity INFO with the correct status code.
Now two findings will be created. 
1) insecure_redirect severity high with redirect URL
2) http_status_code with severity info and the redirect message

Fixed file output error in case of insecure redirect

---

testssl.sh

MongoDB listens on port 27017 and will respond to a direct TLS
ClientHello without the need for STARTTLS. Thus, testssl.sh already
mostly works to scan a MongoDB server.
The problem is that MongoDB will also reply to an HTTP GET request with
a mocked up HTTP response, which was tricking the tool into believing it
was dealing with an HTTP server. The response looks like this:
```
HTTP/1.0 200 OK
Connection: close
Content-Type: text/plain
Content-Length: 84
It looks like you are trying to access MongoDB over HTTP on the native
driver port.
```
Thus, the detection algorith must first look for HTTP, then dig deeper
into the body looking for "MongoDB".
The tool output now says:
Service detected:       MongoDB, thus skipping HTTP specific checks

Add support for MongoDB service detection

---

testssl.sh

testssl.sh was inserting two spaces between the CBC ciphers detected by OpenSSL and those detected to `tls_sockets()`. This PR fixes the problem.

Remove extra space in BEAST output

---

testssl.sh

This may not be specific to LibreSSL, but just my local setup. However, when I test using LibreSSL testssl.sh still prints the following message several times:
WARNING: can't open config file: /usr/local/etc/ssl/openssl.cnf
This PR suppresses the error message for several calls to $OPENSSL and so fixes the problem.

Suppress config file warning

---

etc/cipher-mapping.txt
testssl.sh

This PR adds initial support for TLSv1.3 to `tls_sockets()` and for `run_client_simulation()`. It does not change any of the other functions to test TLSv1.3. So, with the exception of `run_client_simulation()`, the functionality added by this PR can only be tested using the `--devel` option.
This PR does not include the ability to decrypt the encrypted portions of the server's response. So, it does not support functions that need to see such things as the server's certificate, status information, or extensions (other than key share).
When sending a TLSv1.3 ClientHello, support for final version of TLSv1.3 is advertised (0x0304) as well as drafts 18, 19, 20, and 21 (0x7F12, 0x7F13,  0x7F14,  0x7F15).

Initial support for TLSv1.3

---

testssl.sh

This PR fixes the use of `has_server_protocol()` in two places.
Currently `std_ciphersuites()` only tries SSLv2 if the server is known to support SSLv2. This changes it to try SSLv2 unless the server is known to not support SSLv2.
In `run_beast()`, tests against the server are run to determine support for TLSv1.2, TLSv1.1, TLSv1, and SSLv3 unless the server is known to support that protocol (i.e., even if `has_server_protocol()` reports that the server does not support the protocol). This changes it so that a test is only performed against the server if `has_server_protocol()` reports that it doesn't know whether the protocol is supported.

has_server_protocol() fixes

---

testssl.sh

In `client_simulation_sockets()` and `tls_sockets()`, don't work to create a `SOCK_REPLY_FILE` that contains the entire server's response (in cases where the response was spread across multiple packets) unless `$DEBUG` is at least 1.

Don't maintain SOCK_REPLY_FILE in non-debug mode

---

testssl.sh

This PR addresses issue #660 for `run_rc4()`, ensuring that support for RC4 ciphers is detected even if no RC4 ciphers are supported with the highest protocol that the server supports.

run_rc4() and #660

---

testssl.sh

CAA record lookups should be performed on the entire DNS tree as per rfc https://tools.ietf.org/html/rfc6844#page-7
```
For example, if a certificate is requested for X.Y.Z the issuer will
search for the relevant CAA record set in the following order:
X.Y.Z
Alias (X.Y.Z)
Y.Z
Alias (Y.Z)
Z
Alias (Z)
Return Empty
```
This is implemented with a simple loop

Make CAA record lookups resolve the entire DNS tree (Fixes #862)

---

testssl.sh

If `run_server_preference()` is performed:
* against a server that supports SSLv3 and that does not have a cipher order; and
* using a version of OpenSSL that does not support SSLv3; and
* with the `--mapping` option set to "rfc" or "no-openssl"
then the "Negotiated cipher per proto" will not show the SSLv3 cipher since `cipher[i]` will be empty.

run_server_preference() bug fix

---

etc/tls_data.txt
testssl.sh

This PR adds support for TLSv1.3 to `run_server_preference()`. It only provides partial support, as it only works if the server supports an earlier TLS protocol (in order to determine whether the server has a cipher order). It also will only show TLSv1.3 as the "Negotiated protocol" if `$OPENSSL` supports TLSv1.3. (Note that PR #826 and #827 are needed in order for `run_server_preference()` to work with an `$OPENSSL` that supports TLSv1.3).
This PR also fixes a bug in which the variable "proto" was defined and used as both a regular variable and as an array.

Add TLSv1.3 support for run_server_preference()

---

testssl.sh

The main parameter (URI of the host to test) is referred to as `<URI>` everywhere in the script, except for in one comment, where it was `<host>`.
So I made this consistent with other uses, by replacing that occurrence by `<URI>`.

Correct small inconsistency in code comment

---

testssl.sh

For ciphers that use the ChaCha20-Poly1305 cipher, LibreSSL shows "Enc=ChaCha20-Poly1305" in the `openssl ciphers -V` command rather than "Enc=ChaCha20(256)" and for some GOST ciphers it shows "Enc=GOST-28178-89-CNT" rather than "Enc=GOST(256)". This causes a problem for `neat_list()` if information is being obtained from `$OPENSSL ciphers -V` rather than from the cipher-mapping.txt file.

Fix problem with LibreSSL encryption names

---

testssl.sh

This PR adds a check for the Expect-CT header to `run_more_flags()`.
I was forwarded an [announcement](https://groups.google.com/a/chromium.org/forum/#!msg/blink-dev/he9tr7p3rZ8/eNMwKPmUBAAJ) this morning that support for public-key pinning is being deprecated in Chrome. The [announcement](https://groups.google.com/a/chromium.org/forum/#!msg/blink-dev/he9tr7p3rZ8/eNMwKPmUBAAJ) included a recommendation for web developers to use the Expect-CT header. The Expect-CT header is mentioned in an [announcement](https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/tgn5R-58iek) about Chrome and in an IETF Internet Draft, [draft-ietf-httpbis-expect-ct](https://datatracker.ietf.org/doc/draft-ietf-httpbis-expect-ct).
This PR just causes testssl.sh to print the contents of the Expect-CT …

Add check for the Expect-CT header

---

testssl.sh

This PR fixes a false positive in `std_cipherlists()`. Currently, `sclient_success` is not initialized (so it initially set to 0). If a server is being tested that only supports TLSv1.3, the `--ssl-native` option is not used, and `run_protocols()` is run before `run_std_cipherlists()`, then for many of the calls to `std_cipherlists()` no tests are run and so `sclient_success` remains at its initial value (0), which is treated as success (i.e., the server supports at least one of the ciphers in the list).
The reason this happens is that in the testing loop, the TLSv1.3 test is skipped if the list of ciphers doesn't include any TLSv1.3 ciphers (and only the "Strong encryption" test includes TLSv1.3 ciphers) and the tests for each of lower versions of SSL/TLS is skipped since it was already …

Fix false positive in std_cipherlists()

---

Dockerfile
Dockerfile.md

Added a Dockerfile for using testssl.sh with docker.
Usage:
docker run -t testssl.sh example.com
Ability to pull image from docker hub:
docker run -t dr4y/testssl.sh example.com

Dockerfile for testssl.sh

---

testssl.sh

When the certificate signature algorithm is RSA-PSS and OpenSSL 1.1.1 is used `$cert_sign_algo` contains some trailing space characters, which causes the algorithm not to be recognized in the case statement. This PR fixes the problem by removing any trailing space characters from `$cert_sign_algo`.
I came across this problem as a result of noticing a new [commit](https://github.com/openssl/openssl/commit/e6cccb5f0523f5a61f5d963ca1708d02e3e83ccc) to the OpenSSL master branch, which changes the [indentation of the Signature Algorithm line](https://github.com/openssl/openssl/commit/d1453d60a58b3e5de24a71d6fa65938629c144c8) when printing a certificate.
I did a comparison of the output of OpenSSL 1.0.2-chacha and the current master branch of OpenSSL and discovered that there are other …

Yet another fix for OpenSSL 1.1.1

---

testssl.sh

When the server's response to the ClientHello message (i.e., the ServerHello, Certificate, ServerHelloDone) is split across more than one packet, the current call to `tls_sockets()` in `run_heartbleed()` only retrieves the first packet. As a result, sometimes when `run_heartbleed()` believes that it is reading the response to the Heartbleed payload it is actually reading the continuation of the response to the ClientHello message.
This PR fixes the problem by indicating in the call to `tls_sockets()` that the ephemeral key is needed. This causes `tls_sockets()` to continue requesting additional packets until it receives the ServerHelloDone.

Fix run_heartbleed()

---

testssl.sh

This PR adds TLSv1.3 support for the negotiated protocol and cipher in `run_server_preference()`. This mostly addresses #893, however, `run_server_preference()` will not work with a TLSv1.3-only server as it will fail when trying to determine whether the server has a cipher order.
Note that with this PR `run_server_preference()` will not always provide consistent results when testing a server that does not support TLSv1.3 using a version of OpenSSL prior to 1.1.1. If it is determined before running `run_server_preference()` (using `run_protocols()`) that the server does not support TLSv1.3, then `run_server_preference()` will use OpenSSL to determine the negotiated protocol and cipher. However, if it has not yet been determined that the server does not support TLSv1.3, then …

Add TLSv1.3 support for negotiated protocol and cipher

---

testssl.sh

This PR just removes some extra spaces in the printing of TLS extensions in `parse_tls_serverhello()`.

Remove extra spaces

---

testssl.sh

The default STARTTLS_SLEEP timeout was increased to 10 seconds in
d1e7498. This caused MySQL connections to timeout. Quick fix is to
parameterize the timeout and pass in 1 again.
Better future fix is to read MySQL as binary packets, parsing the fixed
sized header, to then read the variable sized payload. Doing this will
also greatly speed up testing.
This fixes issue #914.

Reduce read timeout for MySQL back to 1 second

---

testssl.sh

If a supported_versions extension was included in the ClientHello, then check that the version returned by the server was included in the ClientHello's supported_versions extension.
OpenSSL will respond to a TLSv1.3 ClientHello that only specifies 0304 in its supported_versions extension with a ServerHello that specifies whatever draft of TLSv1.3 it currently supports (e.g., 7F16). The result is that `run_protocols()` incorrectly reports that OpenSSL supports TLSv1.3 "final" in addition to whatever draft version it supports.
This PR fixes that problem by treating it as a failed connection when the ClientHello offers only 0304 and the ServerHello specifies something else (e.g., 7F16).
Performing this check is actually a requirement for clients in Section 4.2.1 of draft-ietf-tls-tls13-22. …

Compare selected version against supported_versions

---

testssl.sh

If certificate-based client authentication is required by the server, then most HTTP-related checks are skipped, even if the "--assume-http" flag is used. If `$CLIENT_AUTH` is true, then `$ASSUME_HTTP` is ignored.
In some cases the checks are appropriately skipped, since the tests cannot be performed. In other places, the value of `$CLIENT_AUTH` is used as a hint as to whether HTTP is being used. For example, in `run_tickbleed()`:
```
if [[ "$SERVICE" != HTTP ]] && ! "$CLIENT_AUTH"; then
outln "--   (applicable only for HTTPS)"
fileout "ticketbleed" "INFO" "Ticketbleed: not applicable, not HTTP" "$cve" "$cwe"
return 0
fi
```
There are some places, however, where tests are just skipped if both `$CLIENT_AUTH` and `$ASSUME_HTTP` are true, even though the test could be performed. For example, …

HTTP-related checks and certificate based client authentication

---

testssl.sh

This PR adds an additional COLOR level (3). If color is set to 3 then all ciphers are printed according to `pr_cipher_quality()` rather than just the "Negotiated cipher" in `run_server_preference()`.

Color all ciphers

---

testssl.sh

The comma was missing in front of the last finding that is inserted as part of the JSOn footer. THis corrects it and once merged my unit tests should work again.

JSOn output is broken by the JSON footer in combination with mass mode

---

CREDITS.md
Readme.md
doc/testssl.1
doc/testssl.1.md
testssl.sh

This PR adds a test to check whether a server that supports ciphers suites that use RSA key transport (TLS_RSA) are vulnerable to Bleichenbacher attacks (see http://archiv.infsec.ethz.ch/education/fs08/secsem/bleichenbacher98.pdf).

Test for vulnerability to Bleichenbacher attack

---

testssl.sh

The comment at the beginning of the run_robot() function uses the wrong title for the paper. This PR fixes the title and adds a URL.

Correct comment

---

testssl.sh

This PR reduces testssl.sh's use of temporary files by making greater use of pipes. This results in a very slight performance improvement.

Reduce use of temporary files

---

testssl.sh

`get_server_certificate()` uses an `awk` script to extract the certificates from the output of `$OPENSSL s_client` and it then uses the following line to determine how many certificates were found:
```
nrsaved=$(count_words "$(echo level?.crt 2>/dev/null)")
```
If `$nrsaved` is 0, then `get_server_certificate()` returns 1 (indicating failure); otherwise it returns 0 (indicating success).
However, the check for the number of certificates returned doesn't work if no certificates were found, as `$nrsaved` will be set to 1 if no certificates were found:
```
> touch level0.crt
> echo level?.crt
level0.crt
> touch level1.crt
> echo level?.crt
level0.crt level1.crt
> rm level0.crt level1.crt
> echo level?.crt
level?.crt
```
This PR fixes the problem by first checking that level0.crt exists (`-s` …

Fix check for whether certificates were found

---

testssl.sh

This PR adds code to decrypt the encrypted portion of the server's response for TLSv1.3 and to then process any certificates and encrypted extensions. This code supports all 5 TLSv1.3 cipher suites, and so any response can be decrypted as long as the session key can be derived (which requires OpenSSL to support the ephemeral key that was used - see #938).
For the symmetric decryption, the `sym-decrypt()` function uses OpenSSL when possible and internal Bash functions when needed.
For AES-GCM and AES-CCM ciphers `sym-decrypt()` normally uses internal Bash functions, which rely on using `$OPENSSL enc` in AES-ECB mode to generate the key stream and then Bash functionality to XOR the key stream with the ciphertext. With some versions of OpenSSL the AES-GCM ciphers are decrypted using …

Decrypt server's TLSv1.3 response

---

testssl.sh

In TLSv1.2 and below, servers respond to a status_request extension (a request for a stapled OCSP response) by returning an empty status_request extension and then including a CertificateStatus message, which follows the Certificate message. In TLSv1.3 the CertificateStatus response is included as the value of the status_request extension, which now appears as an extension within the Certificate message.
This PR extracts the contents of the status_request extension sent by the server so that it can later be processed in the same way as if it had sent in a TLSv1.2 or below response.

Process TLSv1.3 status_request extension

---

testssl.sh

This PR is similar to #944. If using OpenSSL 1.1.1 to connect to a server that supports TLSv1.3, `run_crime()` will connect to the server using TLSv1.3, which does not support TLS-level compression. So, the server will be reported as "not vulnerable" even if it would use compression for connections at TLSv1.2 and below.
I have not encountered any "live" servers that support both TLSv1.3 and TLS-level compression. I verified this problem by using OpenSSL 1.1.1 to create a server that supports both TLSv1.3 and TLS-level compression:
```
openssl111 s_server -cert cert.pem -key key.pem -accept 8443 -WWW -comp
```
I then tested the server using `testssl.sh --crime` with both openssl111 and OpenSSL 1.0.2-chacha.

run_crime() and OpenSSL 1.1.1

---

testssl.sh

When we scan a service with certificate-based authentication enabled with the `--json-pretty` output, the file generated is invalid:
```
"scanResult"  : [
{
"id"           : "client_auth",
"severity"     : "INFO",
"finding"      : "certificate-based authentication => skipping all HTTP checks"
}                    "protocols"         : [
{
"id"           : "sslv2",
"severity"     : "OK",
"finding"      : "SSLv2 is not offered"
```

Certificate-based auth host scanning produces invalid JSON output

---

testssl.sh

Noticed a typo whilst using the library earlier:
`HSTS timeout 180 days (=15552000 seconds) > 15465600 days`
Should be:
`HSTS timeout 180 days (=15552000 seconds) > 15465600 seconds`
There were some other typos/inconsistencies so I fixed them.

Fix typos in HSTS tests: days -> seconds

---

t/31_badssl.com.t
testssl.sh

This PR adds **breaking changes** to the JSON output parameters ``id`` and ``findings``.
``findings`` in JSON are now more crunchy and don't repeat parts of ``id``. Also ``id`` has changed so that it is more reflecting what has been tested.
**Further changes:**
The change from @dcooper16 wrt TLS_FALLBACK_SCSV still has to be changed in the same manner.
It also finally merges @dcooper16 PR about key usage and extended key usage extensions. ``fileout()`` handing has been added, it also works on BSDish sed flavors.
As the cipherlist checks in the beginning have been less and less to do with the OpenSSL standard lists a change to remove the word "standard" was long overdue. That has been addressed now also in the code and in the  JSON/CSV output.
``$HOSTCERT`` has now an ``.pem`` file …

New JSON id and findings (breaks things!)

---

testssl.sh

This PR defines an `extract_certificates()` function in order to remove some redundant code from `get_server_certificate()`. Currently, nearly identical code appears in two places in `get_server_certificate()` to extract certificates from the output of `$OPENSSL sclient`, in one place for SSLv2 responses and in another for SSLv3 through TLSv1.2. The code to get the certificates used with TLSv1.3 (see https://github.com/dcooper16/testssl.sh/tree/extended_tls_sockets) would have added a third place where this same code would be needed. This PR allows the code to be written once and used in all three places.

Define extract_certificates() function

---

testssl.sh

In the output created by `certificate_info()`, the "Server key size" line labels an elliptic curve key as "ECDSA." This PR changes the label to "EC." I believe this a more correct label since ECDSA is a signature algorithm, not a key type. Also, while unlikely, an elliptic curve key in a certificate may be used for ECDH (e.g, in TLS_ECDH_RSA_WITH_AES_128_CBC_SHA) rather than ECDSA.
Note that this change does not impact the JSON or CSV output, since the corresponding `fileout` command already uses `"$cert_keysize EC bits"`.

Label elliptic curve public keys as "EC"

---

testssl.sh

In TLSv1.3, if a HelloRetryRequest needs to be sent and the call to `tls_sockets()` includes additional request extensions (other than key_share or cookie), then `resend_if_hello_retry_request()` adds an extra comma between extensions in the value sent to `socksend_tls_clienthello()`, which creates errors. This commit fixes the problem by removing the extra comma.

Fix HelloRetryRequest

---

testssl.sh

This commit adds TLSv1.3 support for run_server_defaults(). It uses `get_server_certificate()` to run separate checks for RSA and ECDSA certificates by sending TLSv1.3 ClientHello messages with different signature_algorithms values. A similar change is made to `certificate_transparency()` in order to check for certificate transparency support for certificates returned over TLSv1.3. It also modifies the check for certificates offered without SNI by including an option to use `tls_sockets()` with servers that support TLSv1.3 if OpenSSL does not support TLSv1.3.

Add TLSv1.3 support for run_server_defaults()

---

testssl.sh

`determine_trust()` uses the output of `$OPENSSL verify` to determine whether OpenSSL can construct a valid certification path for the server's certificate. If it does not find a string of the form "error [1-9][0-9]? at [0-9]+ depth lookup:" in the output, then it assumes that validation was successful. In current versions of OpenSSL, when this error is created it is printed to stdout, but in OpenSSL 1.1.1 is it printed to stderr. Since testssl.sh only checks the output sent to stdout, it incorrectly treats all certificates as valid if OpenSSL 1.1.1 is used.
This PR fixes the problem by checking the text that is sent to both stdout and stderr.
This PR also fixes a typo in the call to `$OPENSSL verify` which resulted in the environment variables SSL_CERT_DIR and SSL_CERT_FILE not being set …

Fix determine_trust() for OpenSSL 1.1.1

---

testssl.sh

Hi @drwetter,
As per your request, the commas are all removed to keep consistency in the JSON outputs.
Regards,
Alex

Remove CVEs commas for better consistency

---

testssl.sh

testssl.sh was recently changed to store the text printout of the host's certificate in a file, `$HOSTCERT_TXT`, and then use this file in some places rather than calling `$OPENSSL x509 -in $HOSTCERT -text -noout`. There was a problem, however, in cases in which the server had more than one certificate (including cases in which the server returned an unrelated certificate when sent a ClientHello w/o SNI), since the contents of `$HOSTCERT_TXT` was not always being updated whenever `$HOSTCERT` changed.
This PR fixes that problem by replacing the previous solution with a less ambitious one. In this version, the global variable is eliminated and instead `run_server_defaults()` stores a text version of each certificate it finds in an array. This value is then passed to …

Fix HOSTCERT_TXT

---

testssl.sh

If extra extensions are provided to `socksend_tls_clienthello()`, then `socksend_tls_clienthello()` needs to determine what extensions were provided so that it doesn't add any of these extensions a second time. The code that was looping through the extra extensions to get the extension IDs was using the wrong value for the length of the string. This PR fixes the error.

Bugfix for extra extensions

---

etc/tls_data.txt
testssl.sh

Support for X448 was recently added to the development branch of OpenSSL 1.1.1. This PR adds an X448 key pair to etc/tls_data.txt (that was generated using OpenSSL 1.1.1) and adds X448 to the supported_groups extension for TLS 1.3 ClientHello messages.

Add X448 support in TLS 1.3

---

testssl.sh

The implementation of `read_sigalg_from_file()` was changed on January 29 in https://github.com/drwetter/testssl.sh/commit/88cd5528e72a923b26386666d5e76b69849f387b. The new implementation does not work correctly in cases in which `read_sigalg_from_file()` is called with `$TMPFILE` as as parameter.
The current implementation of the function is:
```
read_sigalg_from_file() {
local hostcert_txt="${1//pem/txt}"
[[ -r "$hostcert_txt" ]] || $OPENSSL x509 -noout -text -in "$1" 2>/dev/null >$hostcert_txt
awk -F':' '/Signature Algorithm/ { print $2; exit; }' $hostcert_txt
}
```
When called using `$TMPFILE` (`/tmp/testssl.XXXXXX/tempfile.txt`), `hostcert_txt` is set to `$TMPFILE`, and since this file exists and is readable, the next line does nothing and the final line tries to read the signature …

Revert change to read_sigalg_from_file()

---

testssl.sh

Drafts 25 and 26 of TLS 1.3 were issued in early March. Neither made any change that is relevant to testssl.sh.
This PR adds checks for these two drafts.

TLS 1.3 drafts 25 and 26

---

testssl.sh

This PR adds a missing check for local TLSv1.3 support in cipher_pref_check(). If the "--ssl-native" mode is being used and $OPENSSL does not support TLSv1.3, then a warning should be displayed indicating that TLSv1.3 cannot be checked rather than displaying the same results as if the server did not support TLSv1.3.

Check for TLSv1.3 in OpenSSL

---

testssl.sh

When using testssl.sh with the current development branch of OpenSSL 1.1.1, `determine_trust()` incorrectly reports that "openssl <= 1.0.2 might be too unreliable to determine trust." The problem is that `find_openssl_binary()` is not correctly extracting the version information. The version is "1.1.1-pre3-dev," but `find_openssl_binary()` extracts:
```
OSSL_VER_MAJOR: 1
OSSL_VER_MINOR: 1.13
OSSL_VER_APPENDIX: -pre-dev
```
This PR fixes the problem and also eliminates the use of external functions in extracting version information for $OSSL_VER.
Note that this code makes a change from the current code. Currently, $OSSL_VER_APPENDIX is intended to contain anything from $OSSL_VER that comes after $OSSL_VER_MAJOR.$OSSL_VER_MINOR. For example, if $OSSL_VER is 1.1.0-dev, then …

Extracting OpenSSL version information

---

testssl.sh

As requested in #1019, this PR changes `find_openssl_binary()` so that $OSSL_VER_APPENDIX contains everything from $OSSL_VER that appears after $OSSL_VER_MAJOR.$OSSL_VER_MINOR.

Fix OSSL_VER_APPENDIX

---

testssl.sh

`parse_tls_serverhello()` checks `$TLS_CLIENT_HELLO` for a supported_versions extension, and if it contains one, checks that the negotiated version is listed in that extension. However, while `$TLS_CLIENT_HELLO` is always set in `socksend_tls_clienthello()` it is not set by `client_simulation_sockets()` (or any of the functions that `client_simulation_sockets()` calls). As a result, when the server's response to a client simulation is parsed, `parse_tls_serverhello()` may compare the negotiated version against the supported_versions extension from a ClientHello message from a previous test.
This PR fixes the problem by having `client_simulation_sockets()` set `$TLS_CLIENT_HELLO`.

Fix client simulations

---

testssl.sh

This PR fixes three issues related to the testing for RFC 7919 DH groups in `run_pfs()`:
* If the RFC 7919 DH groups are supported for both TLSv1.3 cipher suites and non-TLSv1.3 cipher suites, then the list of supported groups is printed twice.
* The finding that is used for CSV/JSON files includes the word "offered" after the list of groups, which is inconsistent with other findings.
* Since the `$ffdhe_offered` is only used to determine whether to test for use of RFC 7919 DH groups with non-TLSv1.3 ciphers, this flag should only be set if a non-TLSv1.3 cipher that uses ephemeral DH is found.

Fix RFC 7919 DH groups

---

testssl.sh

https://github.com/drwetter/testssl.sh/commit/b2be380b5465bcf8a8fc028d943a2687df10c8f8 inadvertently changed `MASS_TESTING_CMDLINE` to be a read-only variable. This causes mass testing to fail, since in mass testing the value of `MASS_TESTING_CMDLINE` is set to the command line for each child test.

Fix mass testing

---

utils/update_client_sim_data.pl

Two GREASE ciphers currently appear in https://api.dev.ssllabs.com/api/v3/getClients: 0x3A3A for Chrome 57 and 0xAAAA for Chrome 65.
update_client_sim_data.pl currently only recognizes 0x3A3A as a GREASE cipher and so prints a "FIXME" for 0xAAAA. This PR fixes the problem by adding all 16 ciphers from https://tools.ietf.org/html/draft-ietf-tls-grease-00 to update_client_sim_data.pl.

update_client_sim_data.pl and GREASE ciphers

---

utils/update_client_sim_data.pl

https://api.dev.ssllabs.com/api/v3/getClients incorrectly indicates a highestProtocol of 771 (TLS 1.2) for clients that support TLS 1.3, which leads `run_client_simulation()` to incorrectly report "No connection" if the client would have actually connected using TLS 1.3.
This has been addressed by manually editing etc/client-simulation.txt to set the highest_protocol to 0x0304 for the clients that support TLS 1.3.
This PR modifies update_client_sim_data.pl to automatically apply the fix for clients that support TLS 1.3 in order to avoid a possible regression when etc/client-simulation.txt is updated.

TLS 1.3 clients in update_client_sim_data.pl

---

testssl.sh

There is currently a problem if mass testing is being performed, JSON and/or CSV output is to be produced, the parent process calls `fileout()`, and each child process have its own output file for the JSON and/or CSV output. The can be seen, for example, with the following:
```
testssl.sh --openssl=openssl_1.1.1 --file test_servers.txt --csvfile output_dir --jsonfile output_dir
```
A call will be made in the parent process to report that openssl_1.1.1 has "No engine or GOST support via engine." `fileout()` will try to write to output_dir, which will result in an error.
This PR fixes the problem by checking that the file to be written to is not a directory (as is already done in `html_out()` for HTML output).
NOTE: At some point, a change should be made so that all of these checks are …

JSON and CSV output problem with mass testing

---

testssl.sh

This PR was developed in response to #845. It adds to the list of ciphers used to determine whether the server has a cipher order in order to help avoid cases in which testssl.sh cannot determine a cipher order.
In order to create this list I scanned thousands of servers in order to determine what ciphers they support, including (1) about 20 thousand U.S. government web sites, (2) all of the sites listed at badssl.com, (3) all of the test servers listed at https://github.com/tlswg/tls13-spec/wiki/implementations, (4) about 30 additional non-U.S. government sites, and (5) one server configured as described in #845. I scanned each of these servers using OpenSSL 1.0.2-chacha, 1.0.2o, and 1.1.1.
Then I ran the collected information through a script that created the updated list. For each …

Update ciphers for server preference

---

testssl.sh

In general, a CA only needs to keep the status information for a certificate until it expires. So, once a certificate has expired, the information provided about it in a CRL or OCSP response may no longer be reliable. The certificate may no longer be listed as revoked, even it had been revoked at some point before it expired.
So, this PR changes `certificate_info()` to only check CRLs for revocation status if the certificate has not expired.

Don't check expired certificates

---

testssl.sh

At the moment the code for downloading a CRL seems to only work if the URL is an HTTP or HTTPS URL. It fails if the URL is an LDAP URL. The `wget` command does not support LDAP and when `curl` retrieves data from an LDAP URL it stores the result in LDIF format, which `http_get()` cannot currently convert into a PEM-encoded CRL.
This PR addresses the issue by skipping the revocation check for any URL that does not begin with "http".

non-HTTP cRLDistributionPoints

---

testssl.sh

testssl.sh was inserting two spaces between the CBC ciphers detected by OpenSSL and those detected to `tls_sockets()`. This PR fixes the problem.
This issue was previously fixed by #838 (https://github.com/drwetter/testssl.sh/commit/87fe0c15da90e60ce999f6711c40e9faa0a1a3a2), but that fix was accidentally removed by the next commit: https://github.com/drwetter/testssl.sh/commit/f3dc53f554f02bf8a74f1970e4c035a012fe0be7.

 Remove extra space in BEAST output

---

testssl.sh

`ldap_get()` incorrectly returns 0 if `curl` indicates an error.

ldap_get() should fail if curl fails

---

testssl.sh

In some cases the OCSP URI contains multiple components in the path (e.g., http://www.example.com/OCSP/myOCSPresponder).
This PR changes `check_revocation_ocsp()` to remove all components in the path, rather than just the final component, when extracting the host name from the URI for the host header.

HTTP URLs with multiple components in path

---

testssl.sh

The current code for extracting the validity dates for certificates assumes that the strings "Not Before" and "Not After" will appear exactly once in the pretty-print of the certificate. In most cases that works. However, there are a few server certificates that include the private key usage period extension, which also includes "Not Before" and "Not After" lines. The result is that the current code does not correctly extract the start date and end date from any certificates that have private key usage period extensions.
This PR fixes the problem and also speeds up extraction of the dates by only using Bash internal functions.
The pretty-print of a certificate begins as follows:
```
Certificate:
Data:
Version: 3 (0x2)
Serial Number: ...
Signature Algorithm: ...
Issuer: ...
Validity
Not …
```

Fix extraction of certificate validity dates

---

testssl.sh

This PR improves the handling of error responses when checking status using OCSP. It can handle a few types of errors:
* When the responder just returns an error (e.g., "Responder error: unauthorized").
* When the response cannot be verified (e.g., invalid signature, expired certificate).
* When the response is valid ("Response verify OK"), but there is a problem with the response for the individual certificate (e.g., information is too old, or status is "unknown").

OCSP error handling

---

testssl.sh

This PR fixes problems with `check_revocation_crl()` sometimes reporting that a certificate is revoked even when it isn't, and with `check_revocation_ocsp()` sometimes reporting "error querying OCSP responder" even if the OCSP responder provided a good response. The most common reason for this to happen is when OpenSSL cannot validate the server's certificate (even without status checking). PR #1051 attempted to get status checking to work even in cases in which the server's certificate could not be validated. Based on some feedback provided, this PR instead addresses the problem by not checking status if `determine_trust()` was unable to validate the server's certificate.
In some cases the server's certificate can be validated using some, but not all of the bundles of trusted …

Fix false "revoked" results for CRL and OCSP checking

---

testssl.sh

Some vulnerability tests such as Heartbleed may be flagged as offensive by an IDS. To skip such tests I propose an environment variable OFFENSIVE which can be set to false, if the user so desires.
I have not fully researched which tests are actually offensive (e.g. those injecting unusual payloads) and which tests mimic fairly normal user behaviour (e.g. those using RC4). But you probably get the idea.
Of course some people may consider any type of reconnaissance (with or without testssl.sh) as offensive... :-)

Add option to skip offensive vulnerability tests

---

testssl.sh

Just as some servers will fail if the length of the ClientHello is between 256 and 511 bytes (see RFC 7685), it seems that some servers (or a middlebox sitting in front of the servers) will fail if the length of the ClientHello is 522, 778, 1034, ... bytes (i.e., if length **mod** 256 = 10). I have also encountered one server that will also fail if the length of the ClientHello is 526, 782, 1038, ... bytes (i.e., if length **mod** 256 = 14).
In the case of that one server, the first ClientHello sent by run_pfs() was exactly 1038 bytes, and so run_pfs() was reporting that the server didn't support any PFS ciphers even though it did.
This PR addresses the problem in two ways. First, it modifies socksend_tls_clienthello() so that if the length of the ClientHello would be more than 511 bytes …

A ClientHello length intolerance bug

---

testssl.sh

As described in #1113, some servers will fail if the length of the ClientHello message is 522, 778, 1034, ... bytes (i.e., if length mod 256 = 10) or 526, 782, 1038, ... bytes (i.e., if length mod 256 = 14). This commit avoid this issue for normal testing by adding a 5-byte padding extension to the message if the length would otherwise be one of these lengths.

Avoid ClientHello size bug

---

testssl.sh

In `run_grease()` there is a mismatch between the severity level of findings as printed and as sent to `fileout()`. Problems are labeled as medium when printing, but as CRITICAL in the call to `fileout()`. This PR fixes the problem by changing CRITICAL to MEDIUM.

Fix run_grease() severity levels

---

testssl.sh

This PR reduces the number of public keys that are included in the key_share extension for a TLS 1.3 ClientHello.
When creating the key_share extension for a TLS 1.3 ClientHello, `generate_key_share_extension()` generally omits the public keys for larger finite-field groups (ffdhe3072, ffdhe4096, ffdhe6144, and ffdhe8192) so that the extension will not be overly large.  However, the extension that it creates is still much larger than what is created by other software.
For a generic TLS 1.3 ClientHello, `socksend_tls_clienthello()` offers 7 groups in the supported_groups extension (P-256, P-384, P-521, X25519, X448, ffdhe2048, ffdhe3072) and 6 public keys in the key_share extension (P-256, P-384, P-521, X25519, X448, ffdhe2048). While the largest public key is omitted, this still creates a …

Send fewer key shares

---

testssl.sh

This PR removes the changes that were added in #1113. As noted in the conversation for #1113, it was eventually determined that the actual bug was related to the first message fragment being too short rather than the overall length of the message. So, the warning message that is displayed by the code is misleading. In addition, if changes are made to avoid TCP fragmentation, then this code will no longer even test for intolerance to short message fragments.
I have tried creating a test that intentionally sends the first part of the ClientHello as a short segment as a replacement for this test, but so far the code does not seem to produce consistent results.

Revert #1113

---

testssl.sh

This PR is also based on #1139, but it addresses ECDH keys rather than DH keys. When `run_pfs()` prints the list of elliptic curves offered, it colors each curve according to its quality (based on key length). However, the severity level used when the list is sent to `fileout()` is always "INFO". This PR changes the call to `fileout()` to make the severity level be based on the quality of the shortest curve that the server offers.

Send ECDHE quality to fileout()

---

testssl.sh

At the beginning of run_server_preference(), if the attempt to connect to the server is unsuccessful, a message is printed listing all of the ciphers in $list_fwd and $tls13_list_fwd:
>      no matching cipher in this list found (pls report this): DES-CBC3-SHA:RC4-MD5:DES-CBC-SHA:RC4-SHA:AES128-SHA:AES128-SHA256:AES256-SHA:ECDHE-RSA-AES128-SHA:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA:ECDH-RSA-DES-CBC3-SHA:ECDH-RSA-AES128-SHA:ECDH-RSA-AES256-SHA:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:DHE-DSS-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:AES256-SHA256:ECDHE-RSA-DES-CBC3-SHA:ECDHE-RSA-AES128-SHA256:AES256-GCM-SHA384:AES128-GCM-SHA …

Only list supported ciphers

---

testssl.sh

As a result of #276, `run_server_defaults()` makes several attempts to find certificates that a server offers if the ClientHello is for TLSv1.2 and no SNI is offered. However, these tests are unnecessary if it is already known that the server does not support TLSv1.1.
This PR modifies `run_server_defaults()` so that the the TLSv1.1-only tests are skipped if the server is known to not support TLSv1.1.

Don't run TLSv1.1 tests if server doesn't support TLSv1.1

---

testssl.sh

This PR fixes a bug in `get_cipher()` - one that also appears in `sclient_connect_successful()`.
The code currently assumes that cipher names contain only uppercase letters and numbers. However, ciphers that do not provide authentication include "anon" in the name, which is written in lowercase.
This PR fixes the problem by allowing lowercase letters to appear in cipher names (except in the first portion of the name).
Note that no change was made to similar code in `get_protocol()`, since the line in `get_protocol()` only matches TLSv1.3 ciphers, which do not contain any lowercase letters.

Fix get_cipher()

---

testssl.sh

This PR fixes two bugs in `determine_optimal_proto()`.
First, `sslv2_sockets()` returns 3 if the connection was successful.
Second, if all connection attempts using `tls_sockets()` were unsuccessful, it is possible that `$TEMPDIR/$NODEIP.parse_tls_serverhello.txt` will not exist, so copying it or grepping it will lead to an error. Checking that `$proto` is not `22` will fix this as `$proto` will be empty if `$OPENSSL s_client` was used and it will be `00`, `01`, `02`, `03`, or `04` if `tls_sockets()` was used and the connection was successful with some protocol higher than SSLv2.

Fix determine_optimal_proto()

---

testssl.sh

When `run_server_preference()` is run on a server that only supports SSLv2 it incorrectly reports that the server has a cipher order. The reason for this is that `$list_fwd` and `$list_reverse` only include one SSLv2 cipher.
In SSLv2 the server sends a list of all ciphers it supports in common with the client and the client chooses which cipher to use. As a result, the server cannot enforce a cipher order for SSLv2.
So, this PR fixes the problem in `run_server_preference()` by skipping the test for whether the server enforces a cipher order if `$OPTIMAL_PROTO` is -ssl2 and simply declares that the server does not enforce a cipher order.
Note that this PR is somewhat dependent on #1194, as #1194 needs to be applied in order for `$OPTIMAL_PROTO` to be set to -ssl2 when testing an SSLv2-only …

Fix run_server_preference() for SSLv2 only server

---

testssl.sh

As Dirk commented in #1199, TLS_GOSTR341094_RSA_WITH_28147_CNT_MD5 uses an RSA certificate, not a GOST certificate. So, this PR moves that cipher suite (0xff, 0x00) from the GOST list to the RSA list.
According to etc/cipher-mapping.txt, TLS_GOSTR341094_RSA_WITH_28147_CNT_MD5 uses RSA for both authentication and key exchange, so this PR places it on the list of cipher suites that uses RSA for encryption rather than signatures.

TLS_GOSTR341094_RSA_WITH_28147_CNT_MD5 uses an RSA certificate

---

testssl.sh

With OpenSSL 1.1.0 (and maybe other versions), the `ciphers` function lists many cipher suites that are not actually supported by the `s_client` option. This PR fixes that by using the `-s` option whenever `$OPENSSL ciphers` is used to obtain a list of cipher suites supported by OpenSSL. According to https://www.openssl.org/docs/manmaster/man1/ciphers.html:
```
-s
Only list supported ciphers: those consistent with the security level, and minimum and
maximum protocol version. This is closer to the actual cipher list an application will
support.
```
When the `-s` option is used along with `-tls1`, OpenSSL 1.1.0 will not list any ciphers that only work with TLSv1.2. So, `prepare_debug()` needed to be changed to correctly populate `ossl_supported_tls`, which is supposed to be a list of all …

Use -s option with OpenSSL ciphers

---

testssl.sh

There is currently a bug in `determine_optimal_proto_sockets_helper()`. In two places there is code of the form:
```
tls_sockets ...
if [[ $? -eq 0 ]]; then
...
elif [[ $? -eq 2 ]]; then
...
fi
```
This code does not work as intended since the second check (`elif [[ $? -eq 2 ]]`) is actually comparing the results of the first check to 2 rather than the results of the call to `tls_sockets()`.
This PR fixes that problem and also speeds up the code. Since `tls_sockets()` sets `$DETECTED_TLS_VERSION` to the protocol version that was negotiated, there is no need to scan `$TEMPDIR/$NODEIP.parse_tls_serverhello.txt` for this information.

determine_optimal_proto_sockets_helper() speedup and bug fix

---

testssl.sh

This is a very minor fix to remove some unnecessary escape characters which cause an error generating JSON output for an OCSP error state.

Fix escaping error in JSON output for OCSP stapling check

---

testssl.sh

This PR addresses the following issues raised by shellcheck:
```
In ../github/testssl_2.9dev_20190409b.sh line 1133:
if [[ "$BASH_VERSINFO" == 3 ]]; then
^-- SC2128: Expanding an array without an index only gives the first element.
In ../github/testssl_2.9dev_20190409b.sh line 4301:
tmpfile_handle $FUNCNAME.dd
^-- SC2128: Expanding an array without an index only gives the first element.
In ../github/testssl_2.9dev_20190409b.sh line 4388:
tmpfile_handle $FUNCNAME.dd
^-- SC2128: Expanding an array without an index only gives the first element.
In ../github/testssl_2.9dev_20190409b.sh line 4657:
tmpfile_handle $FUNCNAME$1.txt
^-- SC2128: Expanding an array without an index only gives the first element.
In ../github/testssl_2.9dev_20190409b.sh line 5327:
tmpfile_handle …
```

Fix shellcheck issue SC2128

---

etc/client-simulation.txt

... as it may indicate this is a recent version
but version 17 is infact 5,5 years old.
If you configure the server side this is misleading!
See https://download3.operacdn.com/pub/opera/desktop/

Remove opera client simulation

---

testssl.sh

Currently the `--outfile`, `-oa`, `--outFile`, and `-oA` options assume that the \<fname\> being provided is to be used as a filename, unless it is "auto." However, all of the individual options (e.g., `--logfile`) allow for a directory name to be provided instead of a file name.
This PR changes the handling of the `--outfile`, `-oa`, `--outFile`, and `-oA` options so that if a directory name is provided, the files are created in that directory.

The -outfile, -oa, -outFile, and -oA options should accept a directory

---

testssl.sh

This PR changes `run_protocols()` so that, when using `tls_sockets()`, support for TLSv1.3 is only marked as `pr_svrty_best()` if the final (RFC 8446) version is supported. It also changed run_protocols() so that support for TLSv1.3 is marked as `pr_svrty_best()` if OpenSSL is used (i.e., if the `--ssl-native` option is specified).
One potential issue is that the `--ssl-native` version assumes that if OpenSSL supports TLSv1.3 it supports the final (RFC 8446) version of the protocol. If the tester is using a development version of OpenSSL 1.1.1 rather than the final version, then the protocol test will actually be indicating whether the server supports the same draft version of OpenSSL as the `$OPENSSL` being used to perform the tests.

Mark only TLSv1.3 final as pr_svrty_best

---

testssl.sh

... as occasionally they showed up when using dig which
made the rDNS output look like it's not supposed to be

Remove " " ";" in rDnS

---

CHANGELOG.md
testssl.sh

This PR addresses #316 and #1280: it implements server name indication
also for STARTTLS which has been supported by a number of server
implemantations, in the meantime.
Also it does a final polish to David's pwnedkeys PR #1274 a while back:
UI improvement and detection of network problems.
In addition to PR #1279 it introduces a env variable to devel
mode so that "CERT_COMPRESSION=true ./testssl.sh --devel <params> <target>"
can be used to explore certificate compression on a host.

SNI STARTTLS, minor polish

---

testssl.sh

CERT_COMPRESSION was initialized with false in 912cd906d27f0288cf5230dffee5f875d6a362e9  so so that the variable was always false. This PR fixes that. In addition a informational line
that the new TLS extension has been added (if $DEBUG >3).
Also determine_optimal_proto() is not being run if devel mode ($do_tls_sockets) is enabled.
Furthermore as David added HAS_ZLIB in #1279 as a global, run_crime() now makes use of it too.

Added HAS_ZLIB in run_crime(), declaration of CERT_COMPRESSION fixed

---

testssl.sh

Decription was added using the (future) ETSI's name ETS [1]. Also added as a comment MITRE's CVE data using ETS, amended with NIST's entry in NVD
[1] EFF's interpretation: extra terrible security https://www.eff.org/deeplinks/2019/02/ets-isnt-tls-and-you-shouldnt-use-it

"eTLS" -> ETS

---

testssl.sh

In `emphasize_stuff_in_headers()` there is a check of the `$COLOR` value, which checks whether `$COLOR` is 2. It should check whether `$COLOR` is 2 or higher.

Fix typo in check of $COLOR

---

testssl.sh

As noted in #1288 with some terminal settings under Linux there appeared some ~garbage on the screen.
This PR fixes that by partly reverting 695d02157a2c452598fedbc24ae69809a067592f . At least now and under an older OpenBSD like 6.2 this doesn't seem to be necessary (anymore).

Fix terminal codes / tput

---

.travis.yml
t/07_isJSON_valid.t
testssl.sh

Travis updated the container images so that the perl
reference to 5.18 was outdated. We use now 5.26 which
works, however we should consider to be more flexible.
JSON::Validator didn't compile in the container. Thus
we switched to just use 'JSON'. That also supports JSON
pretty. For the future we should just test for valid JSON
in all unit test files as it is more effective.

Fixes for travis

---

Dockerfile.md

Provides an example of how to create output files in the host filesystem when using Docker.

Output files to host when using Docker

---

Dockerfile.md

As discussed in #1307 the docker userid / file system access rights needed to be taken into account.
Also the markup file was slightly reordered for better readability

Resort and polish

---

testssl.sh

This should address the issues #1319 and #1320 *if* `idn` is available on the system used to test those cases, and my corresponding feature request in #1321 
This takes approach number 1 for #1321 and does several tests to determine how to handle the entered URI:
1. We test if there are non-ASCII characters in the provided URI.  If there are not any non-ASCII characters in the provided URI, then we accept the URI as entered and continue on, processing the URI as we would normally in the 3.0 branch.  Otherwise, we continue on, as we have a second test to run before we can handle the IDN and convert to punycode.
2. If the test revealed that there are non-ASCII characters in the URI, the next test we do is to see if the `idn` binary is available, using Bash's `command -v` call.
1. If `idn` …

Add IDN/punycode support for non-ASCII URIs (#1319, #1320, #1321)

---

testssl.sh

This PR gives depreciation warnings to TLS 1.0/1.1 and doesn't mark the absence of TLS 1.2 as medium anymore when TLS 1.3 is supported.
Details see commit messages

Protocol improvements

---

testssl.sh

The Finding of other_headers such as "Referrer-Policy" during file output are displayed as `$header: $HEADERVALUE` instead of only `$HEADERVALUE` as the good_headers. This leads to duplicate information e.g. in the JSON output file.

remove duplicate header name for other_header in file output

---

Dockerfile

... to Dockerfile.
Drill's IDN support needs to be checked

Add idn support to Dockerfile

---

testssl.sh

There is a problem if a TLSv1.3-only server is tested using the OpenSSL 1.0.2-chacha binary and `$OSSL_SHORTCUT` is true.
`$HAS_NO_SSL2` is set to `true` when `find_openssl_binary()` is called with OpenSSL 1.0.2-chacha. `/usr/bin/openssl` does not have the `-no_ssl2` option, but the second call to `find_openssl_binary()`, after setting `$OPENSSL` to `/usr/bin/openssl`, does not set `$HAS_NO_SSL2` to `false`. So, later calls to `$OPENSSL s_client` include the `-no_ssl2` option, resulting in connection failures.
This PR fixes the problem by modifying `find_openssl_binary()` to ensure that every OpenSSL-dependent variable is set by this function.

Reset OpenSSL dependent variables

---

testssl.sh

There are a few places where testssl.sh sends a TLS 1.2 (or TLS 1.3) ClientHello and expects the server to respond with a ServerHello as long as it supports TLS 1.2 (or TLS 1.3) or earlier.
`run_protocols()` performs a fairly thorough check for a server's ability to handle version negotiation, but the problem may also be caught by `determine_optimal_sockets_params()`, if the server rejects a TLS 1.2 ClientHello even though it supports some earlier protocol version.
In the future, we could try to make use of `$OPTIMAL_SOCKETS_PROTO` in order to make testssl.sh work a bit better with servers (if any still exist) that don't handle version negotiation correctly. At the moment, though, this PR just prints a warning to the user that the server is buggy, and that this may lead to problems in the …

Warn if bad version negotiation detected

---

testssl.sh

... as it was moved to determine_optimal_proto(), see #1336.
LF added in message when TLS13 only

Remove double TLS13 only handling

---

testssl.sh

PR #1336 included logic to pre-test the server side with sockets
and/or with openssl. However when the user supplied --ssl-native
sockets were never tested before. As a result ALL_FAILED_SOCKETS
was still true, so that the final eif statement complaint erroneously
that sockets didn't work but openssl does.
Also Travis complaint.
This PR fixes it by checking SSL_NATIVE to the final part of the
if statement.
One could also test sockets before and then set ALL_FAILED_SOCKETS
appropriately but that would only make sense if the socket methods
like run_robot() or run_heartbleed() would check ALL_FAILED_SOCKETS
first.
At the moment I went for this as it is easier and the case that sockets
aren't working but openssl does seems not very likely.

Squash message to use ./bin/openssl.* when --ssl-native is supplied

---

testssl.sh

This PR fixes a bug in `modify_clienthello()` that occurs when client simulation is being performed, the ClientHello contain an SNI extension, and `$SNI` is empty. In the case, `modify_clienthello()` should just skip over the SNI extension and not include one in the modified ClientHello. However, the code currently only skips over the 2-byte extension type. The result being that the remainder of the extension is included in the modified ClientHello. This PR fixes the problem by ensuring the `$offset` is advanced whether or not `$SNI` is empty.

Fix client simulation bug

---

testssl.sh

'IPv4 address in header' shows body content if there is no match with the specified patterns.
Probably the HEADERFILE should end on the first empty line.
Please check if this works for all supported platforms or if there are any side effects caused by this approach before merging.

'IPv4 address in header' shows body content

---

testssl.sh

1) Add another pattern to the first sed line because the SEDs tested so far do not seem to be fine with header containing x0d x0a (CRLF) -- which is the usual case. So we also trigger on any sign on a single line which is not alphanumeric (plus _)
2) Replace second sed line -- the desperate endeavors ;-) to parse for the start of an html file -- by search for ``<`` or ``{`` maybe with leading blanks. So that if the first pattern doesn't match here at least JSON files won't be catched 
See #1351

Changes to HTML header parsing

---

testssl.sh

In `run_drown()`, `$jsonID` is set to "DROWN" and most calls to `fileout()` are of the form
```
fileout "$jsonID" ...
```
However, one call is written as
```
fileout "DROWN" ...
```
This PR changes this one call to be consistent with the others. This does not change the functionality of the program.

Use $jsonID rather than literal string

---

testssl.sh

At the moment, `$do_starttls` is initialized to `true` in `initialize_globals()` and then it is set to `true` again in `parse_cmd_line()`, if the `--starttls` command line option is used. Presumably the intention was to set `$do_starttls` to `false` in `initialize_globals()`.

Fix do_starttls initialization bug

---

testssl.sh

This PR fixes a minor bug in `parse_tls_serverhello()`. In some cases the server's entire response is not retrieved. In these cases, it is possible that the response from the server ends with a portion of a handshake message.
The loop at the beginning of `parse_tls_serverhello()` extracts the various handshake and alert messages from the server's response. If it gets to the end of the response, and what is at the end is not a small (< 10 byte) fragment of a message, it should just ignore that fragment and `break` out of the loop. At the moment, however, `parse_tls_serverhello()` just continues in the loop rather than breaking out. This has not been a problem up to now, since `$msg_len` is usually set to a positive value from a previous iteration of the loop, which causes the loop to end. …

Fix parse_tls_serverhello() bug

---

testssl.sh

This PR is an attempt to fix #1163 by running separate tests for a server cipher order preference for TLSv1.3 and for SSLv3 - TLSv1.2.
If the server supports TLSv1.3, then a test is performed to determine whether the server enforces a cipher order to TLSv1.3. A separate test is performed for SSLv3 - TLSv1.2 unless it is known that the server does not support any of these protocols.
If the server enforces a cipher order for SSLv3 - TLSv1.2, but not for TLSv1.3, then `cipher_pref_check()` is not called for TLSv1.3, since `cipher_pref_check()` is intended to show the cipher order that the server enforces. As TLSv1.3 will be the negotiated protocol if it is supported, the negotiated cipher for TLSv1.3 will already be presented.
This PR still has one major flaw, which may create a problem when …

Separate server preference test (cipher order) for TLS 1.3

---

testssl.sh

The printf format string in `f5_ip_oldstyle()` is incorrect. It works most of the time, but in cases where the hexadecimal output is less than 8 characters, it fails.

fix bug in f5_ip_oldstyle() printf format string

---

testssl.sh

This fixes a bug e.g. when supplying a proxy by a DNS name, testssl couldn't resolve the name as the HAS_ variables initialized by ``check_resolver_bins()`` was done later than ``check_proxy()``.
The patch just puts ``check_resolver_bins()`` earlier in  "main"

Earlier initialisation of DNS HAS_* related vars

---

testssl.sh

This PR fixes a minor problem with `run_protocols()` in "--ssl-native" mode if `$OPENSSL` does not support TLS 1.3. Currently, the warning message that `$OPENSSL` does not support a protocol is printed when `run_prototest_openssl()` is called. This causes a problem for the output if `$OPENSSL` does not support TLS 1.3, since the `run_prototest_openssl()` is called before the results for TLS 1.2 are printed. The result is something like this:
```
SSLv2      not offered (OK)
SSLv3      not offered (OK)
TLS 1      offered (deprecated)
TLS 1.1    offered (deprecated)
Local problem: /home/cooper/Desktop/testssl.sh/bin/openssl.Linux.x86_64 doesn't support "s_client -tls1_3"
TLS 1.2    offered (OK)
TLS 1.3     NPN/SPDY   not offered
ALPN/HTTP2 http/1.1 (offered)
```
This PR moves the printing of …

Fix issues with run_protocols() in --ssl-native mode

---

testssl.sh

When running in debugging mode, HAS_DIG and friends was
still false as check_resolver_bins() was called too late.
This amends basically bac0f66112c4d6b490fb1183b4cdfc379f961a62 .
In cases where a certificate has two CNs, the output contained
a linefeed. This replaces the line feed by a space.

Move check_resolver_bins again, handle double CN

---

testssl.sh

When `tls_sockets()` is used for `run_protocols()`, for each protocol version the results will indicate whether the server responded to a ClientHello for that protocol version with (1) a ServerHello for that same protocol version, (2) a ServerHello for a different (hopefully lower) protocol version, or (3) a handshake failure.
Currently, however, `run_prototest_openssl()` does not distinguish between cases in which the server responds with a ServerHello for a different (hopefully lower) protocol version and cases in which the server responds with a handshake failure. This PR changes `run_prototest_openssl()` so that it distinguishes between these two cases (as long as `$OPENSSL` supports the protocol version specified in the ServerHello).
Making use of the additional information provided …

Enhance run_protocols() in --ssl-native mode

---

testssl.sh

* remove 2x resumption
* [[ ${SESS_RESUMPTION[2]} =~ clientauth ]] isn't needed.
otherwise fileout needs also to be changed

Add minor output polish for session resumption and client auth

---

testssl.sh

I was amazed to see what your script can do without client certificate.  Yet alpha-level support for client certs can be easily added by injecting relevant options via s_client_options() function.
Status: works for me ;-)
Usage:
$ export keyopts="-cert path/to/cert.pem -CAfile path/to/cert.pem"
$ ./testssl.sh [usual options]
cert.pem may be single file containing pem-encoded:
- certificate key (not encrypted)
- client certificate
- any number of intermediate certificates

Quick'n'dirty client certificate support for s_client

---

testssl.sh

Currently `sub_cipherlists()` and `pr_cipher_quality()` use different numbers for the same cipher quality ratings. `sub_cipherlists()` uses:
> -2 = pr_svrty_critical, -1= pr_svrty_high, 0 = pr_svrty_low, 1 = pr_svrty_good, 2 = pr_svrty_best
while `pr_cipher_quality()` uses:
> 1 = pr_svrty_critical, 2 = pr_svrty_high, 3 = pr_svrty_medium, 4 = pr_svrty_low
> 5 = neither good nor bad, 6 = pr_svrty_good, 7 = pr_svrty_best
This PR changes `sub_cipherlists()` (and `run_cipherlists()`) to use the same numbers for cipher quality as `pr_cipher_quality()`. It does not change any of the ratings assigned to ciphers by `run_cipherlists()` or `pr_cipher_quality()`, so the two are still not in alignment. But, hopefully using the same numbering in both functions will make it a bit easier to compare them …

Align cipher rating numbers

---

testssl.sh

testssl.sh hiccups when a user supplied after --json*/--html/-csv
a filename instead of using the corresponding  --json*file/--htmlfile/-csvfile
arguments, see #1397.
This PR adresses that in a sense that it tries to detect to following
argument of --json*/--html/-csv. If that matches a suspected filename
it bails out using fatal().
This is not intended to be perfect (when the pattern doesn't match)
but catches the user error in an early stage. See also #1398

Catch user error using --json/--html and friends

---

testssl.sh

When printing out HTTP security headers, `run_security_headers()` uses `out_row_aligned_max_width()`, since some headers are very long and need to be wrapped. At the moment, however, the first line is too long. The problem is that while `"$header $HEADERVALUE"` is printed in the indented area, only `$HEADERVALUE` is passed to `out_row_aligned_max_width()`.
This PR fixes the problem by passing `"$header $HEADERVALUE"` to `out_row_aligned_max_width()` so that the the first line is wrapped at the correct place.

Fix formatting of HTTP security headers

---

doc/testssl.1
doc/testssl.1.html
doc/testssl.1.md
testssl.sh

This PR provides a patch to give users the possibilities to define a socket timeout (in seconds) by supplying the command line parameter --connect-timeout or a value to the environment variable CONNECT_TIMEOUT
Details see commits containing this PR

Connect timeout

---

doc/testssl.1
testssl.sh

Currently there is an `--openssl-timeout` option. However, there is no option to control TCP handshake timeouts. When testing many hosts if any of them is unexpectedly unresponsive (TCP 443 port closed, host down, behind a firewall, etc.) `testssl.sh` will hang for about 2 minutes for each host.
This PR adds the parameter `--connect-timeout` to limit the maximum amount of time to wait for the TCP handshake to complete successfully. The default value is 3 minutes, so that current users of `testssl.sh` should not be affected by this change.
I tested this feature and it seems to be working as intended.

Add --connect-timeout parameter

---

testssl.sh

At the moment, testssl.sh does not correctly derive the handshake traffic keys in the case that the server responds to the initial ClientHello with a HelloRetryRequest. The handshake traffic keys are computed incorrectly because the wrong messages are provided to `derive-handshake-traffic-keys()` for input to the Transcript-Hash calculation:
* `$TLS_CLIENT_HELLO `is not updated to contain the value of the second ClientHello, and so the first ClientHello is being provided to derive-handshake-traffic-keys() as both the first and the second ClientHello.
* In middlebox compatibility mode the server may send a dummy ChangeCipherSpec message immediately after the HelloRetryRequest. Since it is part of the server's response to the initial ClientHello, the ChangeCipherSpec message is included in …

Fix TLS 1.3 key derivation

---

testssl.sh

This PR fixes a couple of places where "$OPENSSL s_client" is called with "-ssl3" even if SSLv3 is not supported.
The fix in `ciphers_by_strength()` is easy, as the issue only occurs if "$using_sockets" is true. If SSLv3 (or TLSv1.3) is not supported, then testing using "$OPENSSL s_client" is skipped and all of the supported ciphers are found using `tls_sockets()`.
The fix for `run_tls_fallback_scsv()` is more complicated. While it is easy to avoid calling "$OPENSSL s_client" with "-ssl3" if SSLv3 is not supported, it is not easy to determine the correct message to present to the user if support for SSLv3 (and possibly also TLSv1.3) is unknown.
For the case in which $high_proto cannot be set, I believe that I have covered all of the possibilities, but am not sure if the correct …

Don't call s_client for unsupported protocol versions

---

doc/testssl.1
doc/testssl.1.html
doc/testssl.1.md
testssl.sh

... and reorder manpages also so that --warnings, --connect-timeout
and --openssl-timeout appear in the "input parameter" section.
The HTML manpage looks in the diff view quite different as previously
another computer was used for converting the source format with ronn(1).
The manpage in (g)roff format was manually edited with .RE / .RS
for provide indented bulletpoints.
See also #1419

Remove --warnings=false from documenation

---

testssl.sh

OpenBSD's grep seems to interpret "-w <EXPR>:" differently
than Linux or MacOSX/FreeBSD in a sense that this doesn't
matchs, see #1430.
This PR fixes that by squashing the w option in all occuorrences.
In addition it removes the SOCKETHEADER if-statement which was
introduced looking forward a while back. It's not happening soon
at least and the variable was not initialized either.

Fixes missing display of HTTP headers under OpenBSDs

---

testssl.sh

See #1429.
OpenBSD 6.6 had an offset with the HTTP header time of  -3600 seconds.
This PR fixes that by adding the GMT time zone to parse_date()'s
HAS_FREEBSDDATE incarnation. That doesn't matter to FreeBSD.
Also now for older OpenBSDs the local and remote time are now
in the same format:
```
HTTP clock skew              remote: Thu, 09 Jan 2020 12:52:32 GMT
local:  Thu, 09 Jan 2020 12:52:02 GMT
``
so that a time difference is easier to spot.

Fix HTTP time for recent OpenBSD

---

testssl.sh

This PR fixes two problems that occur when testing a server that supports TLSv1.3 using OpenSSL 1.1.1 in `--ssl-native` mode.
First, when testing whether the server has a cipher order, the value of `$sclient_success` is checked after each call to `tls_sockets()`, but `$sclient_success` is not to the result of the `tls_sockets()` call. As the goal is just to verify that the connection was successful (and didn't downgrade), `$?` can be checked rather than `$sclient_success`. [When not in `--ssl-native mode` this problem is masked since `$sclient_success` is set to 0 earlier in the function.]
The second problem is that line 6646 tries to copy "$TEMPDIR/$NODEIP.parse_tls13_serverhello.txt", but this file is currently only created (on line 6287) if `tls_sockets()` is used to determine the …

Fix run_server_preference() in --ssl-native mode

---

testssl.sh

`derive-handshake-traffic-keys()` uses the variables `derived_secret`, `server_write_key`, and `server_write_iv`, but they are not declared as local variables of the function. This PR fixes that.

Add missing variable declarations

---

testssl.sh

... if the standard directory /tmp is not allowed to write to. As noted in #1273 this might be the case for Termux on Android.
Looking at #1273 this PT amends #1443 and replaces #1277

Try temp file creation in a different location

---

testssl.sh

Hi,
testssl.sh may report that a server is vulnerable to CVE-2011-1473 (possible DoS due to client-side renegotiation) even if it only allows a limited number of renegotiation attempts. It concludes that after attempting only one renegotiation.
Contrary to other implementations, Node.js and apparently lighttpd, mitigate the issue by allowing a maximum of 3 renegotiation attempts. See [here](https://github.com/nodejs/node-v0.x-archive/issues/2726) for more details.
We propose this patch to handle this scenario. The limit of renegotiation attempts (4) was obtained empirically according to Node.js's behaviour.
João

Avoid false-positives when testing for CVE-2011-1473 / maximum of 3 renegotiation attempts

---

testssl.sh

The CA browser form agreed on a validity period of 825 days or less (https://cabforum.org/wp-content/uploads/CA-Browser-Forum-BR-1.5.3-redlined.pdf, p4).
PR #1427 addressed that. However when an issuer signed/issued a certificate with exactly 825 days, the check reported incorrectly that the life time is too long.
This PR addressed that by adding a second to the calculation. Also the output takes into account that it must be over ('>') 825 days, not '>='.

Add one second for 825 day validity test

---

doc/testssl.1.md
testssl.sh

Hi Dirk,
I had the problem, when scanning a webserver with HTTP basic auth the test for the security headers is not working correctly. I was looking in the help section of testssl for a switch to provide the basic auth credentials but could not find this feature. So I decided to implement it and open a PR on this issue.
Please let me know if anything is missing.
Cheers

Add support for HTTP Basic Auth

---

testssl.sh

* Replace `! -z` with `-n`
* Replace "openssl' with "$OPENSSL"
* Redirect stderr output of $OPENSSL to /dev/null to supress "WARNING: can't open config file: /usr/local/etc/ssl/openssl.cnf" message (see #833)
* Remove unnecessary spaces from `$GET_REQ11` string.

More polishing of http basic auth

---

t/08_isHTML_valid.t
testssl.sh

Several vulnerability checks add a time penalty when the server side only support TLS 1.3 as The TLS 1.3 RFC 8446 and implementations known so far don't support the flaws being checked for.
This PR adds "shortcut" checks for all TLS 1.3, assuming that the TLS 1.3 implementation is correct which seems at this time a valid assumpution. That either saves a TCP connect or at least some logic to be executed.  Also in some cases a TLS 1.3 only server emitted unnecessary warnings, see #1444.
If $DEBUG -eq 1 then it outputs information that a shortcut was used. It doesn't do that in other cases because the screen output seems too obtrusive.
It also adds a shortcut for beast when SSL 3 or TLS 1.0 is is known not to be supported.
This commit readds 747fb039edc329e759aa634fed8a256031808324 which was …

Shortcuts for vulnerability tests for TLS 1.3 only servers

---

testssl.sh

PR #1463 changed run_ssl_poodle() to only run the test if it is known that the server supports SSLv3. However, support for SSLv3 may be unknown at the time run_ssl_poodle() is run (e.g., if the server supports both TLS 1 and SSLv3, and run_ssl_poodle() is the first test performed). So, run_ssl_poodle() should perform testing unless it is known that SSLv3 is not supported.

Fix run_ssl_poodle()

---

testssl.sh

This PR simplifies the code for determining which draft version of TLS 1.3 a server is offering by making use of a simple regular expression and `$BASH_REMATCH` rather than looping through every possible draft version.

Simplify code to determine draft TLS 1.3 version

---

testssl.sh

'-xmpphost' option required in combination with '-starttls xmpp' was missing
in determine_optimal_proto()
Also tweaked a couple of log messages

Fix XMPP starttls
