drwetter/testssl.sh

testssl.sh

Trivial typo fix

---

testssl.sh

Tiny fix for spelling.
@drwetter , as always, take your time. No rush here :)
Cheers,
Peter

FIX: minor spelling issue

---

testssl.sh

This is very nit-picky but in my non-scientific tests it sometimes saves half a second! :-)

Minor optimizations to reduce unnecessary forking

---

testssl.sh

also, align comment blocks for better code readability.
have a great weektend too!

trim all whitespace at EOL, plus spelling typos fixes. 

---

testssl.sh

ADDITION: Show git commit information, to support troubleshooting.

FIX: Show version when specified on command line

---

testssl.sh

Micro commit (added a space to improve readability)

Minor textual fix (added space)

---

CREDITS.md
testssl.sh

Hi Dirk,
I've added a check for TLS_FALLBACK_SCSV support on the server. I bumped the version number of the script to 2.6dev - wasn't sure what else to do with it sorry, so ignore if you like!
Cheers,
Jon

Added a check for TLS_FALLBACK_SCSV

---

testssl.sh

Mac OS X ships with bash 3, not 4 by default (3.2.57 on my 10.10.4 system). The bash case statement fallthrough and continue operators were added in bash 4. This patch removes the use of the operator that was [recently added](https://github.com/drwetter/testssl.sh/commit/b742c543584db71752a09e3362176692373b7278#diff-2b772c01e86977452d2db64b3031f913R3740).
```
$ ./testssl.sh example.com
./testssl.sh: line 3980: syntax error near unexpected token `;'
./testssl.sh: line 3980: `				 ;&'
```
Since the XMPP detection is quite different I considered separating it, but decided to just merge the two `$protocol == "xmpp"` checks inside the existing case rather than separating xmpp support out completely.

Fix syntax error near unexpected token on Mac OS X

---

Readme.md

Extremely small typo fix.. but hey, every character counts :smile:

Minor textual fix

---

testssl.sh

Hello Dirk,
please merge the bug fix.
Best Regards
Thomas

Fix certificate expiration check

---

testssl.sh

Fixes #174

---

testssl.sh

Slight change due to drwetter's comment :)

Added check for availability oftput (Fixes #222)

---

testssl.sh

Support rDNS with mDNS for the private network (192.168) and support for OS X Bonjour with `dig`.

mDNS Fixes

---

testssl.sh

Lamest pull request ever: fixed typo in parameter descriptions

---

testssl.sh

CREDITS.md was called CREDIT.md

Fix filename typo

---

testssl.sh

Show SHA384 certificates as secure

---

testssl.sh

Option to suppress the output of the RFC ciphernames in the cipher checks.

added --mapping=no-rfc

---

testssl.sh

Thanks for the diff file. I has already created such a file and used it to get started merging my changes into the latest version. It just took me a while to get this finished since I was doing a lot of testing, fixing a few minor bugs, and making other minor improvements to the code.

Detect multiple server certificates

---

testssl.sh

The number of .pem files in $INSTALL_DIR/etc is currently hard-coded into determine_trust. This modifies the code so that the number of files can be changed without having to change the code.

Number of trusted certificate files in $INSTALL_DIR/etc/*.pem

---

testssl.sh

use double quotes instead of single quotes
remove newlines from strings

fix json output

---

testssl.sh

Correction of line 3607: new line (\n) corrupted the json format

Correction of line 3607: new line (\n) corrupted the json format

---

testssl.sh

Note: I deleted line 207, "HAS_SSL2=false", since it was a repeat of line 203.

Fix some typos

---

testssl.sh

This PR adds to the list of signature algorithms recognized in certificate_info().

Recognize more signature algorithms

---

testssl.sh

Necessary changes:
* get rid of some \c escapes to printf(1).
* refactor date parsing because GNU date(1) style "-d date-to-parse" works in NetBSD.

porting to NetBSD

---

.gitignore
t/01_badssl.com.t

I would like to see some unit tests for tetstssl.sh so we can check the quality. 
badsll.com provides a good testbed for this.
Ideally an integration between GitHub and Travis CI is set up: https://docs.travis-ci.com/user/languages/perl
@drwetter can you let me know if you like this idea and if you need help setting up Travis CI?
I plan to add more tests to this later.

Lets add some unit tests to testssl.sh - Using abdsll.com work

---

testssl.sh

As was discussed in #122, the PR displays the set of elliptic curves supported by the server for use with ECDHE-* ciphers. Since the ECDHE-* ciphers are PFS ciphers, I added the new code to run_pfs().
Not all versions of OpenSSL support the "-curves" option for "s_client". At the moment, if no curves are found, then the code just doesn't display anything.
It was my original intention to implement the check for supported curves in sockets as well, but I ran into a problem. I originally wrote the sockets version to try to connect to the server with only ECDHE-* ciphers specified and with the Supported Elliptic Curves extension only specifying one curve. If the connection was successful, then I assumed the specified curve was supported. This worked in most cases, however, it appears that …

Determine support elliptic curves for ECDHE- ciphers

---

testssl.sh

`certificate_info()` does not correctly display the Issuer name for CAs that use domain component attributes.
There is a server on the NIST intra-net that I test against that has a certificate issued by a NIST CA, and the issuer name in the certificate is of the form: `/DC=net/DC=example/DC=internal/CN=CAname`
Since there is no organizational name, testssl.sh displays the name as:
```
Issuer                       "CAname" ("")
```
In this PR, if the Issuer name has 'DC=' attributes, but does not have an 'O=' attribute, the "DC=" attributes are combined into a DNS name that is used as if it were the organizational name:
```
Issuer                       "CAname" ("internal.example.net")
```
I should note, however, that I have not been able to find any other examples of TLS server …

CA names with domain component attributes

---

t/01_badssl.com.t
testssl.sh

This PR is intended to address issue #94 (CN <--> hostname match).

CN <--> hostname match

---

testssl.sh

Fixes for two minor typos that were previously included in PR #345.

Fix two minor typos

---

testssl.sh

This PR addresses the "FIXME" in `run_protocols()`:
```
sslv2_sockets          #FIXME: messages/output need to be moved to this (higher) level
```
It also changes `run_drown()` to call `sslv2_sockets()` in order to avoid duplicate code.

Move printing of results out of sslv2_sockets()

---

testssl.sh

This PR is an attempt to address issue #447. If more than one certificate is being displayed, then a parenthetical saying "(in response to request w/o SNI)" is added for any certificate that was obtained using `$SNI=""`.
In addition, if the certificate was obtained without SNI, then `certificate_info()` doesn't call `$OPENSSL s_client` in order to obtain the non-SNI host certificate and it does not display a separate "Trust (hostname)" finding for the non-SNI certificate.

Display SNI information in "Server Certificate" line

---

testssl.sh

`socksend_tls_clienthello()` always includes a server name extension in the ClientHello (for TLS 1.0 and above), even if `$SNI` is empty. If `$NODE` is an IP address, then the IP address is placed in the extension, even though RFC 6066 says that only DNS names are supported in the extension.
This PR changes `socksend_tls_clienthello()` so that the server name extension is only included in the ClientHello if `$SNI` is not empty.

Fix tls_sockets() when SNI empty

---

testssl.sh

s_client's manpage states for -nextprotoneg:
"Empty list of protocols is treated specially and will cause the client to
advertise support for the TLS extension but disconnect just after reciving
ServerHello with a list of server supported protocols."
Consequently, the previous workaround of just quoting an empty variable is
insufficient and the "-nextprotoneg" parameter has to be removed entirely from
the command-line in case of an empty argument.
In other locations where "-nextprotoneg" is used
- its argument cannot be empty ($NPN_PROTOs is initialized to a non-empty value
and set read-only) or
- its argument is intended to be empty (line 3724) or
- the command will not be invoked at all (for-loop parameter, line 3725)
This fixes #467 - again.

Fix handling of empty argument to "-nextprotoneg" parameter

---

testssl.sh

This PR changes `sslv2_sockets()` so that a list of ciphers may optionally be passed as an argument. This will support the use of `sslv2_sockets()` in some places where `$OPENSSL s_client` is currently used.

Allow cipher list to be passed to sslv2_sockets()

---

testssl.sh

just aligns the ANSI output for the single line

remove additional pr_off at the end of sslv2 check

---

testssl.sh

Use `printf` in `asciihex_to_binary_file()` rather than `echo -e -n`

Use printf in asciihex_to_binary_file

---

testssl.sh

This PR allows the caller to provide additional extensions to `tls_sockets()` to be included in the ClientHello. If the caller provides an extension that would have already been included in the ClientHello, then the caller's value for the extension is used rather than the default value.

Allow caller to provide extra extensions to tls_sockets()

---

testssl.sh

This PR fixes two issues related to curve X25519.
First, while OpenSSL 1.1.0 supports curve X25519, it is not included in the output of `$OPENSSL ecparam -list_curves`. I tried several versions of OpenSSL (and one version of LibreSSL), and every version outputs either "Error with command" or "unknown option" in response to `$OPENSSL s_client -curves $curve` if it either does not support the `-curves` option or does not support `$curve`. (When the `-curve` option is supported with `$curve`, a "connect" error is output.)
The second issue is that the "Server Temp Key" line in the output of `s_client` is different for curve X25519. For other elliptic curves, the output is
```
Server Temp Key: ECDH, P-256, 256 bits
```
For X25519 it is:
```
Server Temp Key: X25519, 253 bits
```
So, …

Curve X25519 fixes

---

testssl.sh

This PR fixes the same issues as were fixed in PR #513, but also makes two changes to `parse_tls_serverhello()`:
* It changes the number of bits for curve X25519 from 256 to 253 to match OpenSSL.
* It removes the "ECDH, " from the "Server Temp Key: " line in order to match OpenSSL's output.

Curve X25519 fixes for 2.9dev

---

testssl.sh

This PR adds parsing of the Certificate message to `parse_tls_serverhello()`. If the caller requests that the "full" response be parsed, then the Certificate message is parsed, the server's certificate is placed in $HOSTCERT and the intermediate certificates are placed in  $TEMPDIR/intermediatecerts.pem. The certificates are also added to $TMPFILE, in a manner similar to the output of `$OPENSSL s_client` when the `-showcerts` option is used.

Extend TLS ServerHello parsing (part 3)

---

testssl.sh

The PR changes `run_allciphers()` to use `tls_sockets()` (and `sslv2_sockets()`)rather than `$OPENSSL` unless `$SSL_NATIVE` is set or `$STARTTLS` is non-empty. Using sockets allows `run_allciphers()` to test all ciphers, rather than just those supported by `$OPENSSL`.
Using sockets results in `run_allciphers()` running more slowly, partially since it is testing more ciphers, but mostly since `tls_sockets()` is currently slower than `$OPENSSL` (as noted in #413).
(Note that I broke this PR into two separate commits: the first just fixes some indentation errors in `run_allciphers()` without changing the code and the second contains the actual code changes.)

Use tls_sockets() in run_allciphers()

---

testssl.sh

Client simulations can still use sockets even if the cipher mapping file is missing. If the cipher file is present, then `parse_tls_serverhello()` write the RFC name for the cipher and then `run_client_simulation()` converts that to the OpenSSL name (so that the output is the same as if OpenSSL were used).  This PR changes `parse_tls_serverhello()` so that it writes the OpenSSL name for the cipher if the mapping file is missing, which `run_client_simulation()` can then just display.
This PR also unsets `ADD_RFC_STR` if the mapping file is missing, so that `neat_list()` won't try to display the RFC names for the ciphers.

Additional fixes for no cipher mapping file

---

testssl.sh

This PR address a problem in `run_drown()` when the server does not support SSLv2, but does support multiple certificates or doesn't have an RSA certificate.
One example of the problem can be seen with www.facebook.com. If `run_server_preferences()` is run before `run_drown()`, then the results of `run_drown()` are:
```
DROWN (2016-0800, CVE-2016-0703)          not vulnerable on this port (OK)
make sure you don't use this certificate elsewhere with SSLv2 enabled services
https://censys.io/ipv4?q=A626B154CC65634181250B810B1BD4C89EC277CEA08D785EEBE7E768BDA7BB00 SHA256 A3F474FB17509AE6C5B6BA5E46B79E0DE6AF1BF1EEAA040A6114676E714C9965 could help you to find out
```
If only `run_drown()` is performed, then the result is:
```
DROWN (2016-0800, CVE-2016-0703)          not vulnerable on this port …
```

run_drown() when server has non-RSA certificates

---

testssl.sh

This PR implements `run_cipher_per_proto()` in a manner similar to `run_allciphers()`.

run_cipher_per_proto() speedup + sockets

---

testssl.sh

This PR changes `run_logjam()` to use sockets.

Use sockets for run_logjam()

---

testssl.sh

This PR changes `read_dhbits_from_file()` so that, when the "quiet" parameter is absent, the selected curve is shown in addition to the number of bits. This PR only affects the output of `run_client_simulation()` and the "Negotiated cipher" in `run_server_preference()`.

Show selected curve

---

testssl.sh

This PR changes `run_freak()` to use sockets.
I added two ciphers to `$exportrsa_cipher_list`: EXP1024-RC4-MD5 (0x00,0x60) and EXP1024-RC2-CBC-MD5 (0x00,0x61). So, the list is now as follows:
```
0x00,0x62 - EXP1024-DES-CBC-SHA            TLS_RSA_EXPORT1024_WITH_DES_CBC_SHA                SSLv3      Kx=RSA(1024)   Au=RSA     Enc=DES(56)                    Mac=SHA1     export    
0x00,0x61 - EXP1024-RC2-CBC-MD5            TLS_RSA_EXPORT1024_WITH_RC2_56_MD5                 SSLv3      Kx=RSA(1024)   Au=RSA     Enc=RC2(56)                    Mac=MD5      export    
0x00,0x64 - EXP1024-RC4-SHA                TLS_RSA_EXPORT1024_WITH_RC4_56_SHA                 SSLv3      Kx=RSA(1024)   Au=RSA     Enc=RC4(56)                    Mac=SHA1     export    
0x00,0x60 - EXP1024-RC4-MD5 …
```

Use sockets for run_freak()

---

testssl.sh

Added hostname and target host is either URI or NODE:
```
+    target="$NODE"
+    $do_mx_all_ips && target="$URI"
```
```      
"target host" : "mailbox.org",
"port"        : "25",
"startTime"   : "1485623190",
"scanResult"  : [
{
"service"         : "smtp",
"ip"              : "80.241.60.212",
"hostname"        : "mx1.mailbox.org",
"protocols"         : [
{
```

Better output for --MX in JSON-PRETTY

---

testssl.sh

DNS CAA: drill query support.

---

testssl.sh

`run_server_preference()` prints out the server's Negotiated cipher in a different color depending on the quality of the cipher. However, there is a "FIXME" since CBC ciphers are supposed to be flagged, but it is not easy to identity all CBC ciphers from their OpenSSL names.
This PR partially addresses this. It creates a separate function for printing a cipher based on its quality. Whenever possible it determines the quality of the cipher based on the RFC name. However, if it is provided an OpenSSL name and no cipher-mapping.txt file is available, it will follow the current (imperfect) logic for determining the cipher's quality.
The function also returns a value that indicates the quality of the cipher provided, with higher numbers indicating better ciphers. This return value is used by …

Printing Negotiated cipher

---

testssl.sh

This PR just brings 2.9dev_html up to date with 2.9dev.

Merge PR #646 into 2.9dev_html

---

testssl.sh

This PR re-implements `emphasize_stuff_in_headers()` in the HTML branch to more closely match the version in 2.9dev.

Redo emphasize_stuff_in_headers()

---

testssl.sh

This PR ensures that each HTML file produced by testssl.sh only includes a single header, at the top, and a single footer, at the end. It also tries to ensure that the short-version banner is only placed at the top of the HTML file if (1) mass testing is being performed and (2) the results of each test is being placed in a separate file.
It also moves some of the logic out of main and into `html_header()`.

Fix HTML headers and footers

---

testssl.sh

Fix client simulation in 2.8

---

testssl.sh

Two of the minor bugs that were fixed by #672 in the 2.9dev branch also appear in 2.8.

Fix two minor bugs

---

testssl.sh

This PR improves `out_row_aligned_max_width()` in a few ways:
* It makes better use of bash's string manipulation capabilities in order to simplify the function.
* It improves the function's performance. One of the most costly parts of `out_row_aligned_max_width()` was the while loop to print each entry in the text. Since there is only one place in the code where the entries are not all printed the same way (the list of supported curves printed by `run_pfs()`), the PR changes `out_row_aligned_max_width()` to just return a plain text string, which the calling function prints in the appropriate way. For the curves printed by `run_pfs()`, a new function, `out_row_aligned_max_width_by_entry()` takes care of getting the output from `out_row_aligned_max_width()` and then printing each entry …

out_row_aligned_max_width()

---

testssl.sh

This PR modifies `run_mass_testing_parallel()` so that it may be used in place of  `run_mass_testing()`. This PR does not change the behavior of testssl.sh. In order to actually test it out, line 12682 needs to be changed to call `run_mass_testing_parallel()` instead of `run_mass_testing()`.
In order for the parallel testing to work correctly, some global variables needed to be created. The reason for this is that if testing is interrupted, and `cleanup ()` is called in the parent, then the parent needs to kill all of the child processes before the parent deletes its `$TEMPDIR`. Otherwise, error messages will be created as the child processes try to write to files in the parent's `$TEMPDIR` after that directory has been deleted.
One issue that is unresolved. At the moment, if testing is …

Mass testing in parallel

---

testssl.sh

The new `get_cipher()` helper function was not being used in every place where it could be used.

Use get_cipher() helper function

---

t/02_http.t

It seems that I needed to escape the plus sign in the check for the HTTP clock skew.

Add Travis test for HTML output

---

testssl.sh

There is a comment in the `run_client_simulation()` function that says "FIXME: printf formatting would look better, especially if we want a wide option here."
This PR is an attempt at addressing that FIXME and adding a wide option. The proposed wide option prints the same information as the non-wide option, just with the columns aligned. I didn't add any of the additional information that is displayed by other functions in wide mode, since I thought that made the output too wide.

Add wide option for client simulations

---

testssl.sh

This reverts commit 3d2666ab7903cb5a5ebaf107aa39ccd9c131cbef.
I pushed this custom commit into `oerdnj/2.9dev` and I forgot that the PR would be automatically updated (and you pulled it).

Revert "Downgrade BREACH attack to MEDIUM severity"

---

testssl.sh

Changes for alerting on missing SANs. See issue #733.

Alert on missing SANs

---

testssl.sh

correctly capture return code in starttls_full_read

---

testssl.sh

This PR provides improvements to `run_mass_testing_parallel()`. Currently, `run_mass_testing_parallel()` treats `$MAX_PARALLEL` as the maximum difference between the number of the test whose results were last processed and the number of the most recently started test. This means that test 40 will not be started until the results of test 20 have been processed. I've encountered situations in which tests 21 though 39 have completed, but test 20 is still running, and so no new tests are started.
This PR fixes the problem by checking the status of all running child tests to see if any are complete, rather than just looking at `$NEXT_PARALLEL_TEST_TO_FINISH`. This prevents one slow child test (or a few slow child tests) from slowing up the entire mass testing process.
This PR also changes the …

Improvements to mass testing in parallel

---

testssl.sh

This PR introduces the following changes/improvements to running mass testing in parallel:
* Continuous feedback is provided on the progress of testing, so that testssl.sh doesn't appeared to be frozen, even if it is waiting a long time for a child test to complete. [The feedback text is sent to `stderr` so that it doesn't appear in the log file if the `--logging` option is used.]
* Text sent to `stderr` by a child test is captured and then displayed in context with the appropriate test rather than being displayed at the time the error occurs. [Note that this means that if the `--logfile <logfile>` option is used (with `logfile` being the name of a file), then `logfile` will include both `stdout` and `stderr`.]
* If a test is started but it does not complete (because testssl.sh was …

More improvements to mass testing in parallel

---

testssl.sh

This PR attempts to address the outstanding issues with respect to issue #733, mainly by addressing the rules for when a certificate is obtained without SNI.

SAN_preferred updates

---

testssl.sh

Some trivial cleanups to the postgres starttls code.

Postgres cleanup

---

testssl.sh

According to a discussion thread on the IETF TLS WG mail list (see https://www.ietf.org/mail-archive/web/tls/current/msg19720.html), there is at least one TLS server that will fail if the last extension in the ClientHello contains extension_data of length 0.
Currently, `tls_sockets()` will create such a ClientHello if:
* The padding extension is included, and the length of the ClientHello without the padding data would be between 508 and 511 bytes.
* No padding extension is included, and the caller provides `$extra_extensions` in which the last extension in `$extra_extensions` is empty.
* No padding extension is included, `$extra_extensions` is empty, no ECC cipher suites are offered, and the ClientHello is for TLSv1.1 or below (in this case the next protocol extension would be that last …

Make sure last ClientHello extension is not empty

---

testssl.sh

This PR implements a check for Certificate Transparency support, as proposed in #771.

Certificate Transparency

---

testssl.sh

Currently the call to `$OPENSSL s_client` to obtain the certificate returned by the server when SNI is not provided is in `certificate_info()`, which means that it is called once for each certificate found the various called to `get_server_certificates()`.
This PR moves the call to `$OPENSSL s_client` to `run_server_defaults()` so that the call is made only once, even if more than one server certificate was found.
In addition, in most cases the certificate returned by the server when SNI is not provided will already have been retrieved by `run_server_defaults()` (in rounds 8-14), in which case `$HOSTCERT.nosni` can just be copied from there rather than making an additional call to `$OPENSSL s_client`.

Just get non-SNI certificate once

---

CHANGELOG.stable-releases.txt
CREDITS.md
Readme.md
doc/testssl.1
doc/testssl.1.md

This PR just corrects several typos and spelling errors.

Correct typos

---

testssl.sh

Now several cookies from BIGIP F5 load balancers will be detected. The work stems from the project https://github.com/drwetter/F5-BIGIP-Decoder. It detects all (to me) known incarnations of cookies. If an IP address will be detected it is labeled as information leakage (MEDIUM). Also the encrypted cookie will be detected (INFO level).
In addition other cookies in the HTTP header will appear with a reduced risk -- MEDIUM instead of HIGH.
The code was retabbed with spaces, so there are minor changes appear in the patch/diff.

F5 cookie detection

---

testssl.sh

This PR replaces the use of sed or awk in a few places with bash internal functions.

Use bash internal functions

---

testssl.sh

This PR addresses issue #660 for `run_sweet32()`, detecting if 3DES is used, even if it isn't used with the highest protocol version supported by the server. As with PR #854, this increased robustness comes at the expense of taking additional time to run the test.

Fix #660 for run_sweet32()

---

testssl.sh

This PR adds support for TLSv1.3 to run_std_cipherlists().
This PR also provides a partial fix for #660 - addressing the issue only for run_std_cipherlists(). Rather than testing the server once for each cipher list, it tries the server once for each protocol supported by the server. This makes the testing more robust, but adds significantly to the time it takes to perform the tests.

Add TLSv1.3 support for run_std_cipherlists()

---

testssl.sh

This PR adds TLSv1.3 support for `run_allciphers()`. It also addresses issue #660 for `run_allciphers()`.

Add TLSv1.3 support for run_allciphers()

---

testssl.sh

If testssl.sh is used with OpenSSL 1.1.1 and TLSv1.3 support is enabled, then the check for whether the server has a cipher order will always fail. The problem is that since the call to `s_client` doesn't specify a protocol a TLSv1.3 ClientHello will be sent. However, the call specifies a list of ciphers that doesn't include any TLSv1.3 ciphers. So, OpenSSL will fail with the error: "No ciphers enabled for max supported SSL/TLS version." The solution is to add the "-no_tls1_3" option.
This PR fixes the problem by taking advantage of the recently-added `s_client_options()` function. It adds a "-no_tls1_3" option whenever:
* $OPENSSL supports TLSv1.3
* The command line doesn't specify any protocol: `-ssl2`, `-ssl3`, `-tls1`, `-tls1_1`, `-tls1_2`, or `-tls1_3`.
* The command line includes …

Another fix for OpenSSL 1.1.1

---

testssl.sh

PR #777 introduced a proposed solution to #772. This PR applies the proposed solution wherever it was not applied in #777.

Complete fix of #772

---

testssl.sh

This PR fixes several places where the `read_sigalg_from_file()` helper function isn't being used.

Use read_sigalg_from_file() helper function

---

testssl.sh

This PR adds TLSv1.3 support for `run_cipher_match()`. It also addresses issue #660 for `run_cipher_match()`.

Add TLSv1.3 support for run_cipher_match()

---

testssl.sh

This PR is a continuation of #833.
With additional testing with different options I encountered more places where `$OPENSSL` was printing "WARNING: can't open config file: /usr/local/etc/ssl/openssl.cnf" where testssl.sh was not suppressing the error message.
This PR redirects `stderr` to `/dev/null` or to `$ERRFILE` for several more calls to `$OPENSSL` in order to suppress these warning messages.

Suppress more config file warnings

---

testssl.sh

This PR adds a check for TLSv1.3 support to `run_protocols()`, checking for support for the final version of TLSv1.3 (0x0304) as well as drafts 18, 19, 20, and 21 (0x7F12, 0x7F13, 0x7F14, and 0x7F15).

Add TLSv1.3 support for run_protocols()

---

testssl.sh

This PR changes `run_heartbleed()` to use `tls_sockets()` to send the ClientHello and to read the ServerHello.

Use tls_sockets() for run_heartbleed()

---

testssl.sh

In TLSv1.3, when responding to a HelloRetryRequest, the second ClientHello should be sent through the same socket as the first ClientHello.
This PR adds an option to `socksend_tls_clienthello()` to not open a socket and then uses that option in `resend_if_hello_retry_request()` when sending the second ClientHello.

Don't open new socket for second ClientHello

---

testssl.sh

This PR adds support for TLSv1.3 draft 22. This PR has testssl.sh operate in "middlebox compatibility mode" as described in Appendix D.4 of draft-ietf-tls-tls13-22 to maximize the chances of being able to perform a successful test even if there is a misbehaving middlebox between testssl.sh and the server being tested. Support for drafts 18 through 21 is still maintained.
This PR has been tested against a few different implementations of draft 22 that were made available shortly before draft 22 was posted.

Support TLSv1.3 draft 22

---

testssl.sh

This PR reduces the amount of work `parse_tls_serverhello()` does when processing alert messages when not in debug mode. It delays writing anything to `$TMPFILE` unless `$DEGUG -ge 1` until it has reason to believe that the response was successful. If `$DEBUG` is 0 and alert messages are sent, then no file operations are performed processing the alert messages.
In almost every case, there is no attempt to look at the contents of `$TEMPDIR/$NODEIP.parse_tls_serverhello.txt` unless the connection was successful. So, in most cases, it is okay to not call `tmpfile_handle()` in `parse_tls_serverhello()` unless the connection was successful. There is, however, one place in `run_grease()` where the code reads the contents of `$TEMPDIR/$NODEIP.parse_tls_serverhello.txt` even if the connection was …

Reducing processing of alert messages

---

testssl.sh

Similar to the recently added HAS_PKUTIL (https://github.com/drwetter/testssl.sh/commit/f829878a43098ac3bb146f4905c2fa78d7b90e9e), this PR adds HAS_PKEY, which indicates whether OpenSSL has the `pkey` utility. HAS_PKEY is then checked before attempting to do anything that requires the `pkey` utility.

Introduce property global HAS_PEY

---

testssl.sh

This is the first in a series of PRs to add support for processing the encrypted portions of the server's response in a TLSv1.3 handshake.
This PR adds the code to derive the handshake traffic key needed to decrypt the response (the next PR will add the code to perform the symmetric-key decryption of the encrypted portions of the response).
Since this PR does not make use of the traffic key that it derives, it doesn't yet add any new functionality.
Note that testssl.sh will not always be able to derive the session keys. If the version of OpenSSL that is bundled with testssl.sh is used and the server chooses to use an X25519 ephemeral key, OpenSSL will be unable to perform the shared secret in `derive-handshake-traffic-secret()`. (OpenSSL 1.1.0 supports X25519.) Since X25519 use a …

Derive handshake traffic key for TLSv1.3

---

testssl.sh

In TLSv1.3 servers may send a supported_groups extension, which "SHOULD contain all groups the server supports, regardless of whether they are currently supported by the client."
This PR extracts the contents of the supported_groups extension, if `parse_tls_serverhello()` is to process "all" of the server's response. The contents of the extension are also displayed on the terminal if $DEBUG -ge 3.

Process supported_groups extension

---

testssl.sh

`run_renego()` appears to produce a false positive if OpenSSL 1.1.1 is used and the server being tested supports TLSv1.3 (i.e., the server supports the same draft version of TLSv1.3 as the version of OpenSSL 1.1.1 being used does). This PR fixes the problem by telling calls to `$OPENSSL s_client` in `run_renego()` to not use TLSv1.3.
When testing a server that supports TLSv1.3 using OpenSSL 1.1.1 the server is reported as being VULNERABLE to both "Secure Renegotiation" and "Secure Client-Initiated Renegotiation." It is my guess, however, that these vulnerabilities do not apply to TLSv1.3 connections, and so testing should only be performed using TLSv1.2 or below connections.

run_renego() and OpenSSL 1.1.1

---

testssl.sh

This PR adds support for draft 23, which contains 2 changes that are relevant for testssl.sh. It adds a few new values for the signature_algorithms extension and it changes to extension number for the key_share extension from 40 to 51.
With the change in the extension number, it is no longer possible to send a single ClientHello that works for all supported drafts of TLSv1.3. (I tried sending a ClientHello with two key share extensions, 40 and 51, but that didn't work.) So, this commit adds a test to `determine_optimal_proto()` to determine whether TLSv1.3 is supported and if so whether draft 23 is supported or only some earlier draft (18-22). In subsequent tests, the ClientHello uses the appropriate number for the key share (40 or 51) and specifies the appropriate draft version(s) in the …

Add support for TLSv1.3 draft 23

---

testssl.sh

This PR is intended to improve the functionality of `run_tls_fallback_scsv()`.
The original goal of this PR was to address servers that support TLSv1.3 when using OpenSSL 1.1.1. That does not seem to be an issue, as using `$OPENSSL s_client` with the `-no_tls1_2` flag results in a TLSv1.1 ClientHello, even if `$OPENSSL` supports TLSv1.3. However, if the server supports TLSv1.3, then a message that says "No fallback possible, TLS 1.2 is the only protocol (OK)" isn't entirely correct.
The main issue this PR fixes is some false positives in servers that do not support TLSv1.2. On a few servers that I tested, the current code incorrectly reports "Downgrade attack prevention NOT supported." Some of the servers only support TLSv1, so it should report that fallback is not possible. Another …

run_tls_fallback_scsv() improvements

---

testssl.sh

The branches need to be merge in order to get the json_prefix / json_postfix right

Key usage 

---

testssl.sh

This commit adds support for [TLSv1.3 draft 24](https://tools.ietf.org/html/draft-ietf-tls-tls13-24). The only change between draft 23 and draft 24 is that draft 24 requires the version number of the record layer to be "0303" for a second ClientHello, whereas draft 23 allowed the version number for both the initial and second ClientHello to be "0301".
The current text reads:
```
legacy_record_version  This value MUST be set to 0x0303 for all
records generated by a TLS 1.3 implementation other than an
initial ClientHello (i.e., one not generated after a
HelloRetryRequest), where it MAY also be 0x0301 for compatibility
purposes.
```

TLSv1.3 draft 24

---

testssl.sh

If OpenSSL reports an error, `sclient_connect_successful()` may incorrectly interpret it as a connectivity problem, leading testssl.sh to stop testing before it has completed.
When not using "--ssl-native" mode, this happens if $OPENSSL does not support SSLv3, as both `get_server_certificate()` and `run_beast()` will attempt to connect using SSLv3 even if $OPENSSL does not support it.
When using "--ssl-native" mode, this happens in multiple places if $OPENSSL does not support the protocol being used or if $OPENSSL does not support any of the ciphers that are specified in the command line.
This PR fixes the above problems by adding checks for protocol support or for support for at least one cipher before calling $OPENSSL.
`run_client_simulation()` also has a problem in "--ssl-native" mode …

Fix false connectivity problem error

---

doc/testssl.1
doc/testssl.1.html
doc/testssl.1.md
testssl.sh
utils/ccs-injection.bash
utils/checkcert.sh
utils/curves.bash
utils/prototype.tls-protocol-checker.bash
utils/ticketbleed.bash

`codespell` can be found here: https://github.com/lucasdemarchi/codespell

Fix typos found by codespell

---

testssl.sh

There is at least one server that will fail under some circumstances if the ClientHello offers a compression method other than null.
In OpenSSL 1.1.0 and 1.1.1, s_client will not offer any other compression methods unless the "-comp" option is provided. However, in earlier versions of OpenSSL, s_client will by default offer the DEFLATE compression method, however, this can be disabled using the "-no_comp" option.
This PR addresses the flaw in this server by having `s_client_options()` add a "-no_comp" option to the command line if "-no_comp" is supported and the test doesn't require offering compression.
Since run_crime() requires compression to be offered, `run_crime()` was changed to always add "-comp" to the command line, and then `s_client_options()` was changed to remove "-comp" from …

Don't offer TLS compression by default

---

testssl.sh

https://github.com/tlswg/tls13-spec/wiki/implementations now lists a server that supports TLS 1.3 draft 28, so this PR adds support for drafts 27 and 28.
Since `run_protocols()` now checks for 11 different drafts of TLS 1.3 in addition to the final version, performing a separate test for each draft had become far too time consuming. So, this PR rewrites the check for TLS 1.3 drafts in `run_protocols()` so that the number of tests is proportional to the number of drafts that the server supports rather than the number of drafts that testssl.sh can check for.

TLS 1.3 draft 28

---

testssl.sh

This PR adds the option to query the OCSP server(s) specified in a server's certificate for the certificate's revocation status.

Add OCSP checking

---

testssl.sh

This PR fixes two issues with OCSP checking. First, the syntax for specifying a host header changed in OpenSSL between versions 1.0.2 and 1.1.0. With OpenSSL 1.0.2-chacha, 1.0.2o, and LibreSSL the syntax needs to be "-header Host \<hostname\>". With OpenSSL 1.1.0h and 1.1.1 the syntax needs to be "-header Host=\<hostname\>". I have not been able to test other versions of OpenSSL 1.0.2 or 1.1.0, but am assuming that all versions of OpenSSL 1.1.0 use the same syntax as 1.1.0h.
This PR also fixes a typo in the case of an error, which was causing $code to be set to "empty ocsp response" if the response was not empty rather than if it was empty.

OCSP improvements

---

testssl.sh

According to Section 7.4.2 of RFC 5246, when a server sends its certificate it MUST send a list in which the first certificate is the sender's certificate and "Each following certificate MUST directly certify the one preceding it." testssl.sh currently assumes that the server has populated the list this way and so places the second certificate in the list into `$TEMPDIR/hostcert_issuer.pem`.
However, not all servers have been following this requirement, and so draft-ietf-tls-tls13 (soon to be RFC 8446) only says that servers SHOULD list the certificates in this way and says that clients "SHOULD be prepared to handle potentially extraneous certificates and arbitrary orderings from any TLS version, with the exception of the end-entity certificate which MUST be first."
testssl.sh needs to …

Handle incorrectly populated certificate_list

---

testssl.sh

This PR fixes some issues identified by [shellcheck](https://github.com/koalaman/shellcheck/releases). Please double-check these changes, especially the changes to `f5_port_decode()`.
```
In testssl.sh line 607:
pr_url()     { tm_out "$1"; html_out "<a href="$1" style=\"color:black;text-decoration:none;\">$1</a>"; }
^-- SC2027: The surrounding quotes actually unquote this. Remove or escape them.
In testssl.sh line 608:
pr_boldurl() { tm_bold "$1"; html_out "<a href="$1" style=\"font-weight:bold;color:black;text-decoration:none;\">$1</a>"; }
^-- SC2027: The surrounding quotes actually unquote this. Remove or escape them.
```
These functions should have been enclosing the URLs in quotes, but they weren't. This PR fixes that by escaping the quotes.
```
In testssl.sh line 1284:
tmp=0{$tmp} …
```

Fix some shellcheck issues

---

testssl.sh

Most of the curves that were defined for the supported_groups extension in RFC 4492 have been deprecated in RFC 8422 and RFC 8446. Appendix B.3.1.4 of RFC 8446 says that these deprecated values "are used in previous versions of TLS and MUST NOT be offered or negotiated by TLS 1.3 implementations."
According to a recent discussion on the TLS mail list (see, for example, https://www.ietf.org/mail-archive/web/tls/current/msg26974.html and https://www.ietf.org/mail-archive/web/tls/current/msg26980.html) a TLS 1.3 server implementation may choose to reject a TLS 1.3 ClientHello simply because the ClientHello offers one or more of the deprecated curves.
This PR address this issue by no longer offering the deprecated curves in TLS 1.3 ClientHello messages. This only affects `run_pfs()`, since …

Deprecated elliptic curves

---

testssl.sh

This PR is an attempt to address #1097. I have only been able to test it against jabber.topf.org and against locally created test certificates, so it needs more testing.
The main issue that this addresses is that testssl.sh currently checks against the wrong name for XMPP servers. According to RFC 6120, Section 13.7.2.1:
> - The initiating entity sets the source domain of its reference identifiers to the 'to' address it communicates in the initial stream header; i.e., this is the identity it expects the receiving entity to provide in a PKIX certificate.
So, if the `--xmpphost` option is provided, then the name provided in that option should be compared against the name in the certificate rather than the host name.
`compare_server_name_to_cert()` currently takes the server name to look for …

Name check for XMPP servers

---

testssl.sh

For cipher suites that use ephemeral DH groups, run_pfs() currently only displays information about the group(s) used if the server complies with RFC 7919. In the case of TLSv1.3 this is appropriate, since server can only use the values from this RFC and only if they are offered by the client in the supported_groups extension.
For TLSv1.2 and earlier, however, servers are free to use whatever DH group they want, but run_pfs() only provides information about the group the server uses if the server complies with RFC 7919. (The information is, however, provided by run_logjam()). However, so far no servers comply with RFC 7919's requirement to refuse to negotiate a TLS_DHE cipher if the supported groups extension is present, included DH groups, but none that are supported by the server. There …

Checking for DH groups in run_pfs()

---

Readme.md

Hi - thanks for this awesome tool. 
I had a need to build a lot of pipeline automation around testssl.sh and open sourced two components of it, hopefully will be of use to others. I've added the links at the bottom of the readme. Thanks again for the great tool!

new links to external/related projects 

---

testssl.sh

This PR provides an additional fix for the issue raised by #1159. It defines a third option for the degree of processing that should be performed by `tls_sockets()`: "all+". When "all+" is provided, the processing is exactly the same as for "all" with the exception of the creation of the supported_groups extension. For a TLSv1.3 ClientHello, curves that are not supported by `$OPENSSL` are omitted from the supported_groups extension rather than offering these curves as the least preferred option.
The "all+" option is used in `run_server_defaults()` where, unlike with almost every other call to `tls_sockets()`, a successful connection is of no use unless the response can be decrypted. This is also the case for `run_alpn()`, and so the call to `tls_sockets()` was also changed to "all+" …

Fix #1159 part 2

---

testssl.sh

This PR is an attempt at addressing #1185. According to https://www.etsi.org/deliver/etsi_ts/103500_103599/10352303/01.01.01_60/ts_10352303v010101p.pdf, if eTLS is in use, then the certificate should contain a subjectAltName extension with one or more "names" containing "visibility information." The "visibility information" is encoded as an otherName with a type-id of 0.4.0.3523.3.1 and a value of
```
VisibilityInformation ::= SEQUENCE {
fingerprint         OCTET STRING (SIZE(10)),
accessDescription   UTF8String }
```
The `etsi_etls_visibility_info()` function determines whether the certificate includes an "visibility information," and, if it does, extracts the fingerprints and access descriptions.
This PR is a work-in-progress for two reasons. First, it has not been tested against any …

WIP: Detecting "eTLS" 1.3 (Fix #1185)

---

testssl.sh

This PR fixes two problems with `modify_clienthello()`.
First, the function was incorrectly using the variable `$key_share` instead of `$new_key_share`. Since `$key_share` is defined when `modify_clienthello()` is called from `resend_if_hello_retry_request()`, but not when it is called from `client_simulation_sockets()`, this bug does not seem to result in incorrect behavior, but it should still be fixed.
Second, when this function is used to create a second ClientHello in response to a HelloRetryRequest, it removes the key_share extension from the original ClientHello and then appends the new key_share extension at the end. According to https://mailarchive.ietf.org/arch/msg/tls/8ZKCyamcYFaV90h6nf4MUnSPkEE, however, extensions must appear in the second ClientHello in the same order in …

Fix TLSv1.3 second ClientHello

---

testssl.sh

This PR makes a few improvements to `run_server_defaults()` when run on an SSLv2-only server.
First, it uses `sslv2_sockets()` to test the server rather than `$OPENSSL`, so that it will work even if `$OPENSSL` does not support SSLv2.
Second, it changes `run_server_defaults()` to only call `get_server_certificate()` once if `$OPTIMAL_PROTO` is -ssl2, since calling more than once is a waste - SSLv2 only supports ciphers that use RSA key exchange.
Finally, as some code assumes that `$TEMPDIR/intermediatecerts.pem` will exist, even if it is empty, this PR changes a couple of places that delete `$TEMPDIR/intermediatecerts.pem` to instead make the file empty.

Fix run_server_defaults() for SSLv2-only servers

---

testssl.sh

This PR reorganizes `cipher_pref_check()`. Currently, `cipher_pref_check()` runs a for loop, which loops over each protocol and prints the set of supported ciphers for each protocol. This PR simply places the body of the for loop in a separate function from the loop itself. This allows `cipher_pref_check()` to be called for just a single protocol rather than for all protocols. Another PR will make a similar change to `run_cipher_per_proto()`.
The reason for this change is that `cipher_pref_check()` was only intended to be used in cases in which the server enforces a cipher preference order. Some servers, however, enforce an order for some protocols, but not for others. The change in this PR will make it possible in the future to call `cipher_pref_check()` only for protocols in which the …

Reorganize cipher_pref_check()

---

testssl.sh

This PR reorganizes `run_cipher_per_proto()`. Currently `run_cipher_per_proto()` runs a for loop, which loops over each protocol and prints the set of supported ciphers for each protocol. This PR simply places the body of the for loop in a separate function from the loop itself. This allows the body of the loop to be called for just a single protocol.
While this PR does not change the way that testssl.sh functions, it would allow for a future change in which `run_server_preferences()` called `cipher_pref_check()` for protocols in which the server enforces a cipher order and calls `ciphers_by_strength()` for protocols in which the server does not enforce a cipher order.

Reorganize run_cipher_per_proto()

---

testssl.sh

This PR modifies  `get_server_certificate()` to use `tls_sockets()` rather than `$OPENSSL` for finding certificates using SSLv3 - TLSv1.2, unless `$SSL_NATIVE` is true. Using `tls_sockets()` allows testssl.sh to find certificates used by the server even if the server is only using cipher suites not supported by `$OPENSSL`. This may happen, for example, if the server only supports TLS_ECDHE_ cipher suites with curve X25519 and a version of OpenSSL prior to 1.1.0 is being used. A less likely possibility would be if the server had a certificate with a DH key, and a newer version of OpenSSL that does not support TLS_DH_ cipher suites is being used.
Since `tls_sockets()` cannot be used to obtain session tickets from the server, an additional test for session ticket lifetime needed to be added. …

Use sockets for get_server_certificate()

---

testssl.sh

There is a minor bug when performing `run_server_preference()` if the server cannot handle ClientHello messages with more than 128 ciphers (i.e., `$SERVER_SIZE_LIMIT_BUG` is true) and the server supports at least one cipher in 'CAMELLIA:IDEA:KRB5:PSK:SRP:aNULL:eNULL'.
The problem is that `$OPENSSL s_client` is called with a cipher list such as
```
ECDHE-RSA-AES256-GCM-SHA384:CAMELLIA256-SHA:AES256-SHA256
```
then
```
ECDHE-RSA-AES256-GCM-SHA384:CAMELLIA256-SHA:AES256-SHA256:-CAMELLIA256-SHA
```
then
```
ECDHE-RSA-AES256-GCM-SHA384:CAMELLIA256-SHA:AES256-SHA256:-CAMELLIA256-SHA:-AES256-SHA256
```
and finally
```
ECDHE-RSA-AES256-GCM-SHA384:CAMELLIA256-SHA:AES256-SHA256:-CAMELLIA256-SHA:-AES256-SHA256:-ECDHE-RSA-AES256-GCM-SHA384
```
The last call to `$OPENSSL s_client` produces an error …

Fix check_tls12_pref()

---

utils/make-openssl.sh

- Darwin doesn't build with -static (removed; file name suffix changed to "dynamic" in this case)
- Darwin has a different openssldir (/private/etc/ssl)
- script doesn't fail any more at make clean step in case there is no Makefile yet
- Darwin 64 bit compilation needs ./Configure instead of ./config and an explicit reference to darwin64-x86_64-cc

Update make-openssl.sh: Darwin compatibility

---

testssl.sh

Hi Dirk,
On February 21 you added an extra call to `$OPENSSL s_client` to `get_server_certificate()`:
```
>$TEMPDIR/tlsext.txt
$OPENSSL s_client $STARTTLS $BUGS $1 -showcerts -connect $NODEIP:$PORT $PROXY $addcmd -tlsextdebug -status </dev/null 2>$ERRFILE >$TMPFILE
sclient_connect_successful $? $TMPFILE && grep -a 'TLS server extension' $TMPFILE >$TEMPDIR/tlsext.txt
```
This was in "[collect more TLS extensions](https://github.com/drwetter/testssl.sh/commit/be079acb5eb85617868880057e00250e51e90d1a)", and it was also done in [2.8](https://github.com/drwetter/testssl.sh/commit/2df798289002deeceeda8de8ea280d303fb3f3ae).
I just realized that my recent PR (#669) ignores the results of this extra call to `$OPENSSL s_client` since it passes `$TMPFILE` to `extract_new_tls_extensions()` rather …

Remove extra call to s_client

---

testssl.sh

fix IMAP STARTTLS regexp

---

testssl.sh

which fixes #1234
Also one cat was removed :-) in sclient_connect_successful as it is faster

make --mx and --ip=one to work together

---

t/09_isJSON_valid.t

Current catch: "JSON::Validator" cannot swallow "--json-pretty". Other
validators tried had issues too.
Improvements welcome!
See #1227

PoC added for JSON validation unit test

---

Dockerfile
testssl.sh

Docker minor

---

doc/testssl.1
doc/testssl.1.html
doc/testssl.1.md

it accepts a directory.
This PR adds documenation for it.

Add documentation to  #1245

---

t/20_baseline_ipv4_http.t
t/21_baseline_ipv6_http.t.DISABLED
t/23_client_simulation.t
t/Readme.md

So that other people can easier write unit tests, too.
* die statement if testssl.sh cannot be found from the current path
* comment everything out for JSON
* don't repeat the pattern, use a variable
* use "speaking" variable names
Documentation update

Another (minor) step forwad for unit tests

---

utils/hexstream2cipher.sh

Don't include SSLv2 ciphers in hexstream2cipher.sh

---

etc/client-simulation.txt

* Tor 17
* Android 4.2.2
* IE 7 Vista

Depreciation of more clients

---

testssl.sh

This PR addresses #1176 by adding a check of whether the server's public key appears in the https://pwnedkeys.com database.

Check pwnedkeys.com database

---

testssl.sh

[draft-ietf-tls-certificate-compression](https://tools.ietf.org/html/draft-ietf-tls-certificate-compression) specifies a new TLS extension that allows a client to indicate support for receiving the server's certificates in compressed form. This PR adds initial support for that extension to testssl.sh. It was developed based on an [announcement](https://mailarchive.ietf.org/arch/msg/tls/idYj6mgvrlYBbdSfAOcw19pOv4A) that facebook.com has implemented support for the extension.
This PR does not add a test for a server's support for the new extension, it just adds code to `parse_tls_serverhello()` that will parse a compressed certificate message if one is present in the server's response. So, in practice, the code in this PR will not actually be used until additional code has been added that …

Initial support for certificate compression

---

utils/make-openssl111.sh

Fix https://github.com/drwetter/testssl.sh/issues/1294

Fix "make-openssl111.sh"

---

testssl.sh

Rollup fixes for PostgreSQL via STARTTLS and improvements for MySQL via STARTTLS.
Details see each commit

Psql mysql fix

---

CONTRIBUTING.md
Readme.md

.. also reviewed https://github.com/drwetter/testssl.sh/wiki/Coding-Style

Add CONTRIBUTING.md, docker changes in Readme.md

---

testssl.sh

For some reason CVE-2009-3555 ended up as _Secure Renegotiation_,
whereas CVE-2009-3555 is in fact the _Insecure Client-Side Renegotiation_
vulnerability with the MiTM problem <= OpenSSl 0.9.8k.
This fixes that (see also #1086 and #933, #907) by removing the CVE #
from the output. Also the output was changed for Secure Renegotiation
into supported/not vulnerable vs. Not supported / VULNERABLE
Some comments were added.

Fix misleading CVE in Secure Renegotiation

---

testssl.sh

This PR proactively tries to address cases where the server side adds Null Bytes after or during ClientHello in cases where it should be text only.
Now VAR2=$(< $VAR1) is being replaced by VAR2=$(cat -v $VAR1) which is normally not best practice and also considered a useless use of "cat", see https://web.archive.org/web/20160711205930/http://porkmail.org/era/unix/award.html#uucaletter.
Especially with bash 3.2 (Mac OS X) AND when on the server side binary chars it was reported to not work ok, see #1292.
Performance measurements showed no to barely measureable penalty (at max 1s displayed difference in 9 tries).

Binary string washer (0x00 bytes) (probably) after completed ClientHello

---

testssl.sh

This PR fixes a problem in `run_protocols()` that was introduced by https://github.com/drwetter/testssl.sh/commit/7ec3c6ab997b012b1518903137d84043cf9825a8.
https://github.com/drwetter/testssl.sh/commit/7ec3c6ab997b012b1518903137d84043cf9825a8 changes `run_protocols()` to perform the initial testing for TLSv1.3 support before testing for TLSv1.2 support. The problem with this is that the code for testing TLSv1.3 makes use of the results of the TLSv1.2 testing.
In the current code, Line 5183 looks at the value of `$subret` to determine whether the TLSv1.2 ClientHello resulted in a successful connection. However, `$subret` has not yet been set (it has just been initialized to 0 at the beginning of the function). Since `$subret` will always be 0, the code will try to extract a cipher from …

Fix run_protocols()

---

testssl.sh

This PR fixes a few issues with `run_protocol()`:
* In the case that the call to `tls_sockets "03" "$TLS12_CIPHER"` had a return value of 2, the code determining what results to print was looking at `$DETECTED_TLS_VERSION`. However, the value of this variable was set by the later call to `tls_sockets "04" "$tls13_ciphers_to_test"`. This caused incorrect results in the case of a server that supports TLSv1.3 and TLS1.1 (or earlier), but not TLSv1.2. This PR saves the value of `$DETECTED_TLS_VERSION` in `$tls12_detected_version` and then uses this variable later rather than `$DETECTED_TLS_VERSION`.
* When running in debug mode with a server that does not support TLSv1.3, testssl.sh was printing
TLS 1.3     -- downgradednot offered and downgraded to a weaker protocol"
This PR fixes the output …

More run_protocol() fixes

---

testssl.sh

This PR fixes two issues with finding session tickets when using OpenSSL 1.1.1.
First, if OpenSSL connects to the server using TLSv1.3 and it receives more than one Post-Handshake New Session Ticket, then the "TLS session ticket lifetime hint" will appear more than once in `$TMPFILE`. This will cause the line to appear more than once in `$sessticket_lifetime_hint`, which causes problems when trying to extract the `$lifetime` and `$unit` from `$sessticket_lifetime_hint`.
This PR fixes the first problem by changing the `awk` expression in the lines that set sessticket_lifetime_hint so that only the first line with "session ticket lifetime" is extracted.
The second issue is that some servers (e.g., google.com) return a session ticket for TLSv1.2, but not for TLSv1.3. For such servers, …

Fix session ticket issues

---

testssl.sh

This PR fixes an issue with `sub_session_resumption()` when using OpenSSL 1.1.1.
As noted in #1335, some servers will return a session ticket for TLSv1.2, but not for TLSv1.3.
OpenSSL 1.1.1 does not support the "-no_ssl2" option, and so when using OpenSSL 1.1.1 `sub_session_resumption()` adds `$OPTIMAL_PROTO` to the `$OPENSSL s_client` command line. When `determine_optimal_proto_sockets_helper()` is called, `$OPTIMAL_PROTO` will generally be set to "-tls1_2" (or "-tls1_1" or "-tls1") unless the server is a TLSv1.3-only server. As a result  `sub_session_resumption()` will specify that same protocol on the command line, if OpenSSL 1.1.1 is being used.
If "--ssl-native" is used, however, then `determine_optimal_proto()` will set `$OPTIMAL_PROTO` to "-tls1_3" if the server supports TLSv1.3 …

Fix sub_session_resumption()

---

testssl.sh

This PR modifies `run_protocols()` to use the information collected by `determine_optimal_sockets_params()`. If it has already been determined that a protocol is supported, then no test is run by `run_protocols()` for that protocol. `run_protocols()` will still run a test for a protocol even if it has been determined that the server does not support that protocol. The reason for running the test is to verify that the server handles version negotiation correctly. This could be a TLSv1 server that rejects a TLSv1.2 or TLSv1.3 ClientHello, or it could happen in the opposite direction. At one point there was a server that would respond to an SSLv3 ClientHello with a TLSv1.2 ServerHello.
This PR required a couple of changes to `determine_optimal_sockets_params()` so that additional information …

Use determine_optimal_sockets_params() in run_protocols()

---

testssl.sh

This PR takes advantage of the testing done by `determine_optimal_sockets_params()` in order to simplify `determine_sizelimitbug()`.
By the time that `determine_sizelimitbug()` is called, `determine_optimal_sockets_params()` has already determined whether TLSv1.2 ClientHello with 128 ciphers (including 00FF) sent by `tls_sockets()` works, and it has set `$TLS12_CIPHER` to a list of exactly 128 ciphers (including 00FF) that works with the server. So, `determine_sizelimitbug()` doesn't have to check whether the server supports TLSv1.2 and no longer needs to send tests using 127 or 128 ciphers. `determine_sizelimitbug()` can just perform one test with 129 ciphers, if the server supports TLSv1.2, and use the results to set `$SERVER_SIZE_LIMIT_BUG`.

Simplify determine_sizelimitbug()

---

testssl.sh

by adding "_hint" to the additional information when
testing for DROWN.

Adress #1355

---

testssl.sh

Idn improvements

---

CHANGELOG.md

add IDN etc. -support and David's work on determine_optimal_* functions

Amendments + reordering

---

testssl.sh

added in bda9c02183fddf8e7acc6f5427f1a6460bd03b12

remove blank in output

---

testssl.sh

Fix minor mistake introduced in 61238f1a4f71ac077b414a502f3092c9655572ab

Fix missing negation in check_resolver_bins

---

testssl.sh

This PR enhances support for the latest versions of OpenSSL and LibreSSL.
The development version of OpenSSL at https://github.com/openssl/openssl/ is version 3.0.0-dev. So, checks for OpenSSL versions need to support this version as well. At the same time, the latest versions of LibreSSL are 3.0.0, 3.0.1, and 3.0.2, so version number alone will no longer be sufficient to distinguish between OpenSSL and LibreSSL.
In addition to checks for these new version numbers, this PR addresses a couple of other issues:
- In LibreSSL, the "$OPENSSL ciphers" command will not accept any protocol version other than "-tls1" as a parameter (and even including "-tls1" as an option is described as "deprecated").  So, this PR ensures that "$OPENSSL ciphers" is not passed any protocol version, other than …

Support new OpenSSL/LibreSSL versions

---

testssl.sh

In cases where the probes for reading memory from the server side were not
successful (=not vulnerable) the TCP connection was not shut down properly --
leading to and undefined state and probably causing problems to a consecutive
check. The server side then assumably from time to time just didn't return
anything which caused a integration test (t/08_isHTML_valid.t) to fail
randomly.
This PR properly terminates the TCP socket connection. Also, as sending the
close notification before closing the socket was duplicated in testssl.sh
that went to a separate function.
See comment in #1375:
https://github.com/drwetter/testssl.sh/pull/1375#issuecomment-554424814

Ticketbleed fix: shutting down the connection properly

---

testssl.sh

This PR fixes some indentation issues. The PR is a bit long, but it only makes changes to indentation (except for one comment line, where a trailing space character is removed).

Fix indentation

---

testssl.sh

This resolves a regression introduced with IDN support (see also #1370).
* in check_resolver_bins() the determination of HAS_DIG_NOIDNOUT=true was wrong
* in get_*_record() the check for the bool variable was wrong
* in get_*_record() we shouldn't use quotes as they might be expand to a quoted arg

Fix getting CAA record

---

Dockerfile.md

* add --rm
* better description of output

Housekeeping

---

utils/docker-debian10.tls13only.start.sh
utils/docker-nginx.tls13-earlydata.start.sh

... when e.g. sitting in a German train with bad internet connection ;-)

Handle problem when pulling container fails

---

testssl.sh

* rename actually_supported_ciphers() to actually_supported_osslciphers()
* remove some redundant quotes at rhs of double brackets checks

Minor internal code improvements

---

testssl.sh

This just increases the version number.

fixed verson number to 3.0rc6

---

testssl.sh

* Severity of RC4 in run_cipherlists() is now high as everywhere else
* Same for RC2 and DES. Only Export, NULL and ADH remain critical
* 3DES and IDEA in run_cipherlists() is now medium (see #1393)
* CBC3  SEED 3DES IDEA added in pr_cipher_quality()
* MD5 added to pr_cipher_quality() and labled as high
* double RC2 switch statement removed in pr_cipher_quality()

Bring pr_cipher_quality() and run_cipherlists() in line

---

testssl.sh

As noted in #1418 LLMNR (Link-Local Multicast Name Resolution)
resolution times out when using x as an argument to "-connect".
This PR fixes that by replacing "-connect x" by "-connect invalid."
which is supposedly also generally more "DNS query friendly", see
https://tools.ietf.org/html/rfc6761#section-6.4 .
In addition this PR adds a check in get_common_prime() whether
the openssl version used has pkey support. If not with old openssl
versions and previously testssl.sh terminated after presenting garbled 
output. (This was found as tested how very old version of openssl versions
handle "-connect invalid.")

Fix s_client capability test for LLMNR, add HAS_PKEY

---

testssl.sh

Calculation should be: `$((diffseconds / (3600 * 24)` instead of `$((diffseconds / 3600 * 24 ))`

cert_validityPeriod is wrong.

---

testssl.sh

The expression 'grep -aw "Public-Key:"' hiccuped on the colon
under OpenBSD, so that any bitsize on a certificate had wrong
values, see #1425. (FreeBSD was fine)
This PR fixes that. It updates the expression by using awk and
bash internal functions.
The same problem occured in run_robot(). The strong typing of
pubkeybits had to be relaxed to a dynamic typing, unless we
choose to define a second string variable.

Fix bits errors in OpenBSDs

---

CHANGELOG.md
t/08_isHTML_valid.t
testssl.sh

Details see commits.
Feature request from #1422

Check for certificates with a life time >825 days when issued after 2018/03/01

---

testssl.sh

As stated in #1435 when specifying ``-connect-timeout=20`` AND ``--parallel`` there  was a problem with the file handles of child processes (_testssl.sh: line 10454: 5: Bad file descriptor_).
This PR mitigates that in a sense that both switches can't be used together. There's a check now in parse_cmd_line().
In addition it addresses a problem when fatal() is called and e.g. JSON files haven't been created yet (error message ~ _testssl.sh: line 825: : No such file or directory_). It introduces a global CMDLINE_PARSED which remembers the state whether ``parse_cmd_line()`` has been fully executed or not. Only when the former is the case it allows writing to files. That implies that in main parse_cmd_line() has to be followed by json_header() and similar.

Avoid conflict of parallel mass scanning + connect timeouts

---

testssl.sh

As noted in #1273, there are some environments that will not allow writing to /dev/stdout. PR #1277 was an attempt to address that problem (along with an unrelated problem), but it appears that work on #1277 has been abandoned.
At the moment, "/dev/stdout" is only used as a parameter to `asciihex_to_binary_file` (in fact, most calls to `asciihex_to_binary_file` specify "/dev/stdout" as the file parameter). This PR removes the file parameter from `asciihex_to_binary_file` (and so renames it `asciihex_to_binary`). In most cases, this just means removing "/dev/stdout" as a parameter to the function. In the few cases in which a parameter other than "/dev/stdout" was provided to `asciihex_to_binary_file`, this PR just uses a redirect (">" or ">>") to accomplish the same result as providing the …

Don't write to /dev/stdout

---

testssl.sh

See #1070, kudos @poupas.
In addition it checks whether the first result was positive (in terms of a finding). If so it does 4 rounds and checks the result. So that other servers won't be penalized with 4 seconds.

Reimplement mitigation check (renegotiation->node.js)

---

doc/testssl.1
doc/testssl.1.html
doc/testssl.1.md
testssl.sh

* create roff file and HTML
* add hint to $ENV
Avoid 1x subshell
See #1451.

Last fine tuning for http basic auth

---

testssl.sh

As noted in #1444 a few vulnerability checks don't make sense or aren't working.  This PR addresses the renegotiation and compression checks.
Also a few redundant quotes in parse_tls_serverhello() and run_crime() were removed.

Shortcuts for TLS13 only servers in renegotiation checks

---

testssl.sh

This PR removes what appears to be a copy and paste error introduced by #1463.

Undo copy and paste error

---

testssl.sh

... see also https://github.com/drwetter/testssl.sh/pull/1468#discussion_r369786007

Squash the last futile -msg for $OPENSSL

---

CHANGELOG.md
CREDITS.md

If anything is missing or wrong please let us know or do a PR.
<s>(This is until from earlier time to ~2018. >2019 need to follow)</s>

Update attributions and changes for release

---

testssl.sh

Suppress displaying an error in maketempf()
